import pathlib,json,hashlib,subprocess,re
p=pathlib.Path(r'C:\Users\brand\OneDrive\Documents\dead-street'); out=p/'tools/harold_scale_20260915/hq_upgrade'
base=json.loads((out/'baseline.json').read_text()); report=json.loads((out/'report.json').read_text()); assert not report['errors'] and report['disembark_routes']==12
for f,expected in base['protected'].items(): assert hashlib.sha256((p/f).read_bytes()).hexdigest()==expected, f
for name in ['bake','import','native']: assert not re.search(r'SCRIPT ERROR|ERROR:',(out/(name+'.log')).read_text(encoding='utf-8')),name
head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=p,text=True).strip(); index=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=p,text=True).strip()
files=['battle/geometry/harold_street_catalog.gd','assets/art/harold_frontage/ground.png']; shot=out/'DEAD_STREET_Harold_HQ_Upgrade.png'
receipt={'head':head,'index':index,'checks':report['checks'],'errors':report['errors'],'protected_sources_unchanged':True,'sources':{f:hashlib.sha256((p/f).read_bytes()).hexdigest() for f in files},'screenshot_sha256':hashlib.sha256(shot.read_bytes()).hexdigest(),'screenshot_bytes':shot.stat().st_size,'commit_push':'not performed','owner_visual_acceptance':'pending'}
(out/'completion_receipt.json').write_text(json.dumps(receipt,indent=2))
body='Replaced north_car_2 Cabrillo Lowline with the existing bright azure Volta GT at x20.3 (centre24.02), visibly facing the HQ steps. It is a $68,000 grand tourer, deliberately more conspicuous than the prior modest upgrades and below exotic/endgame tiers. Other11 cars remain unchanged, including the Rancher nearby and inexpensive neighborhood vehicles. Canonical1.6 scale produces a7.44x3.104 body; cover/renderer derive from the same catalog. Ground shadow rebaked3456x1848. Supersedes the Cabrillo choice in harold-scale-04/07 in response to owner correction.\n\nWindows Godot4.7.2 native validation: '+str(report['checks'])+' checks passed, zero errors, all12 attacker exit routes available; all parked bodies clear of scenery and inside asphalt, HQ model/anchor/steps alignment, all available cover and both entrances/alley reachable, actual battle starts. Fresh1440x1000 paused12v12 Orlov/Mercer capture visually inspected. Bake/import/native logs have zero script/engine errors. This is a narrow model/placement correction; prior943+6 checks remain historical evidence, no new full combat benchmark, every convoy combination or broader regression run. Shared view, map renderer, convoy planner/context/arrival service and vehicle catalogue hashes unchanged.\n\nEvidence: tools/harold_scale_20260915/hq_upgrade/{check.gd,report.json,completion_receipt.json,DEAD_STREET_Harold_HQ_Upgrade.png,before/}. Reproduction: Godot --path REPO --script res://tools/harold_scale_20260915/hq_upgrade/check.gd; one-time guarded preparation and sequential bake/import/check runner live in the parent folder. HEAD '+head+'; existing uncommitted work preserved; no staging/commit/push. Owner appearance acceptance pending. Next: owner reviews screenshot, reopen normal live-source Sandbox to see the change.\n'
event='\n\n## 20260915-harold-scale-09 - Conspicuous HQ Volta complete\n\n'+body
for f in ['docs/DEAD_STREET_JOURNAL.md','docs/DEAD_STREET_PROJECT_CONTROL.md','docs/HAROLD_AVE_IMPLEMENTATION.md']:
    target=p/f; assert '20260915-harold-scale-09' not in target.read_text(encoding='utf-8'); target.open('a',encoding='utf-8').write(event)
hive=p/'docs/DEAD_STREET_HIVE_MIND.md'; text=hive.read_text(encoding='utf-8'); lines=text.splitlines()
lines=[('**Active objective (2026-09-15):** Harold HQ-car correction complete and native-validated; the conspicuous blue Volta GT now fronts the steps. Owner screenshot review next. Prior wider street, canonical scale and neighborhood cars retained. See harold-scale-09 and tools/harold_scale_20260915/hq_upgrade/.') if x.startswith('**Active objective (2026-09-15):**') else ('| BUILD / Harold pass | Harold vehicles/street and HQ status-car correction | Volta GT outside steps; '+str(report['checks'])+' focused native checks pass. Updated screenshot ready for owner review. See harold-scale-09; prior943+6 checks are previous-version evidence. |') if x.startswith('| BUILD / Harold pass |') else x for x in lines]
hive.write_text('\n'.join(lines)+'\n\n## 20260915-harold-scale-09 - HQ Volta correction complete\nCanonical bright-blue Volta GT replaces the understated Cabrillo directly outside the steps; other11 cars/street unchanged. '+str(report['checks'])+' focused native checks pass, zero errors; screenshot visually inspected. Owner review next. Source/evidence/limits: tools/harold_scale_20260915/hq_upgrade/ and journal harold-scale-09. No staging/commit/push.\n',encoding='utf-8')
readme=p/'tools/harold_scale_20260915/README.md'; text=readme.read_text(encoding='utf-8').replace('| north_car_2 (x19) | Cabrillo Lowline |','| north_car_2 (x20.3) | Volta GT (owner-requested conspicuous HQ upgrade) |'); readme.write_text('# Current correction: conspicuous HQ Volta\nSee hq_upgrade/README.md for the latest car revision, screenshot and focused validation. The following original pass narrative and943+6 checks describe the pre-correction Cabrillo version.\n\n'+text,encoding='utf-8')
(out/'README.md').write_text('# Harold HQ status-car correction\n\n'+body,encoding='utf-8')
standard=p/'docs/MAP_BUILDING_STANDARD.md'; text=standard.read_text(encoding='utf-8'); text=text.replace('Mostly inexpensive neighborhood transport; Cabrillo Lowline/Rancher Seven are the two modest HQ upgrades.','Mostly inexpensive neighborhood transport; a conspicuous blue Volta GT directly outside the HQ steps and nearby Rancher Seven indicate Saints wealth. Owner correction harold-scale-08/09 supersedes the earlier understated Cabrillo choice.'); standard.write_text(text,encoding='utf-8')
for f in ['docs/DEAD_STREET_HIVE_MIND.md','docs/DEAD_STREET_JOURNAL.md','docs/DEAD_STREET_PROJECT_CONTROL.md','docs/HAROLD_AVE_IMPLEMENTATION.md']: assert '20260915-harold-scale-09' in (p/f).read_text(encoding='utf-8')
print(json.dumps(receipt,indent=2))