import pathlib,json,hashlib,subprocess,re
p=pathlib.Path(r'C:\Users\brand\OneDrive\Documents\dead-street'); out=p/'tools/harold_scale_20260915/hq_red'; base=json.loads((out/'baseline.json').read_text()); report=json.loads((out/'report.json').read_text())
assert not report['errors'] and report['disembark_routes']==12
for f,expected in base['protected'].items(): assert hashlib.sha256((p/f).read_bytes()).hexdigest()==expected,f
for name in ['bake','import','native']: assert not re.search(r'SCRIPT ERROR|ERROR:',(out/(name+'.log')).read_text(encoding='utf-8')),name
head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=p,text=True).strip(); shot=out/'DEAD_STREET_Harold_Red_HQ_Car.png'
receipt={'head':head,'index':subprocess.check_output(['git','diff','--cached','--name-only'],cwd=p,text=True).strip(),'checks':report['checks'],'errors':report['errors'],'protected_sources_unchanged':True,'sources':{f:hashlib.sha256((p/f).read_bytes()).hexdigest() for f in base['owned_before']},'screenshot_sha256':hashlib.sha256(shot.read_bytes()).hexdigest(),'commit_push':'not performed','owner_visual_acceptance':'pending'}
(out/'completion_receipt.json').write_text(json.dumps(receipt,indent=2))
body='Owner rejected the blue HQ car. Replaced only north_car_2 with existing scarlet Veloce Rosso at x20.3 (centre23.94), directly outside Saints HQ steps. Clear sports-car silhouette and Saints red; $89,000, below top-end Arsenal models. Other11 neighborhood vehicles and street unchanged. Canonical1.6 scale gives7.28x3.168 footprint, matching cover/art and rebaked ground shadow. This supersedes Volta choice harold-scale-08/09; blue screenshot and evidence retained as rejected history.\n\nNative Windows Godot4.7.2: '+str(report['checks'])+' focused checks pass, zero errors; all12 attackers have usable transport exit routes, every available cover slot and both entrances/alley reachable, parked bodies clear and inside road, HQ model/footprint/steps alignment and renderer anchor correct. Actual battle starts; fresh1440x1000 paused Orlov/Mercer screenshot visually inspected. Bake/import/native logs error-free. Six protected source hashes unchanged: map renderer/view, arrival/planner/context and vehicle catalog. No full combat benchmark/every convoy/broad regression rerun; older943+6 and blue-version538 results are historical.\n\nEvidence/reproduction: tools/harold_scale_20260915/hq_red/check.gd, report.json, completion_receipt.json, DEAD_STREET_Harold_Red_HQ_Car.png and before/. Native command: Godot --path REPO --script res://tools/harold_scale_20260915/hq_red/check.gd. Parent run_hq_red.py is a guarded one-time preparation/bake/import/check runner, not a general replay script. HEAD '+head+'; no staging/commit/push. Other chats and existing uncommitted work preserved. Next: owner screenshot review; reopen normal live-source Sandbox. Visual acceptance pending.\n'
event='\n\n## 20260915-harold-scale-11 - Scarlet HQ car complete\n\n'+body
for f in ['docs/DEAD_STREET_JOURNAL.md','docs/DEAD_STREET_PROJECT_CONTROL.md','docs/HAROLD_AVE_IMPLEMENTATION.md']:
    target=p/f; assert '20260915-harold-scale-11' not in target.read_text(encoding='utf-8'); target.open('a',encoding='utf-8').write(event)
h=p/'docs/DEAD_STREET_HIVE_MIND.md'; lines=h.read_text(encoding='utf-8').splitlines()
lines=[('**Active objective (2026-09-15):** Harold scarlet HQ-car correction complete/native-validated. Veloce Rosso replaces the owner-rejected blue Volta directly outside the steps; other11 cars/street retained. Owner screenshot review next. See harold-scale-11 and tools/harold_scale_20260915/hq_red/.') if x.startswith('**Active objective (2026-09-15):**') else ('| BUILD / Harold pass | Harold vehicles/street and HQ status-car correction | Scarlet Veloce Rosso outside steps; '+str(report['checks'])+' focused native checks pass. Blue Volta rejected. New screenshot review next; see harold-scale-11. |') if x.startswith('| BUILD / Harold pass |') else x for x in lines]
h.write_text('\n'.join(lines)+'\n\n## 20260915-harold-scale-11 - Scarlet Veloce correction complete\nOwner-rejected blue Volta replaced with canonical scarlet Veloce Rosso outside HQ steps. '+str(report['checks'])+' focused native checks pass; screenshot inspected and owner review next. Other11 cars/street/protected sources preserved. See hq_red/ evidence and journal harold-scale-11. No staging/commit/push.\n',encoding='utf-8')
(out/'README.md').write_text('# Harold HQ scarlet Veloce correction\n\n'+body,encoding='utf-8')
readme=p/'tools/harold_scale_20260915/README.md'; text=readme.read_text(encoding='utf-8').replace('# Current correction: conspicuous HQ Volta\nSee hq_upgrade/README.md for the latest car revision, screenshot and focused validation.','# Current correction: scarlet HQ Veloce\nSee hq_red/README.md for the latest car revision, screenshot and focused validation. Blue Volta revision hq_upgrade/ was rejected by the owner.').replace('| north_car_2 (x20.3) | Volta GT (owner-requested conspicuous HQ upgrade) |','| north_car_2 (x20.3) | Scarlet Veloce Rosso (conspicuous HQ upgrade; replaces rejected blue Volta) |'); readme.write_text(text,encoding='utf-8')
standard=p/'docs/MAP_BUILDING_STANDARD.md'; text=standard.read_text(encoding='utf-8').replace('a conspicuous blue Volta GT directly outside the HQ steps','a conspicuous scarlet Veloce Rosso directly outside the HQ steps').replace('Owner correction harold-scale-08/09 supersedes the earlier understated Cabrillo choice.','Owner corrections harold-scale-08 through11 supersede the understated Cabrillo and rejected blue Volta choices.'); standard.write_text(text,encoding='utf-8')
for f in ['docs/DEAD_STREET_HIVE_MIND.md','docs/DEAD_STREET_JOURNAL.md','docs/DEAD_STREET_PROJECT_CONTROL.md','docs/HAROLD_AVE_IMPLEMENTATION.md']: assert '20260915-harold-scale-11' in (p/f).read_text(encoding='utf-8')
print(json.dumps(receipt,indent=2))