import pathlib,json,hashlib,subprocess
p=pathlib.Path(r'C:\Users\brand\OneDrive\Documents\dead-street'); out=p/'tools/cover_interactions_20260915'; out.mkdir(exist_ok=True); before=out/'before'; before.mkdir(exist_ok=True); (before/'.gdignore').write_text('')
files=['battle/geometry/harold_street_catalog.gd','battle/presentation/tactical_participant_visual.gd','battle/vehicles/battle_arrival_service.gd','gameplay/tactical_actor_presenter.gd','gameplay/tactical_battle_view.gd','gameplay/harold_street_art.gd','gameplay/fleet_vehicle_art.gd']
for f in files: (before/(pathlib.Path(f).name)).write_bytes((p/f).read_bytes())
(out/'baseline.json').write_text(json.dumps({'head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=p,text=True).strip(),'sources':{f:hashlib.sha256((p/f).read_bytes()).hexdigest() for f in files}},indent=2))
event='\n\n## 20260915-cover-interactions-01 - Owner accepts red HQ car; flags cover and stairs\nBrandon: "Much better" for the scarlet Veloce, then concerning cover interactions and specifically "And the stairs". Record red HQ-car choice OWNER-ACCEPTED; cover/pose presentation is a new issue, not covered by prior reachability checks. BUILD is inspecting native parked/arrival vehicle and stair-wall interactions. Source reading identifies3.2px facing-dependent occupied-cover visual nudge plus fixed .85-world static standoff and closely spaced vehicle door/body slots as suspects; do not call causes proven before native inspection. Exact source backups/hashes in tools/cover_interactions_20260915/before and baseline.json. Preserve wider street/car choices, range/HUD and concurrent weapon-card/comparison work. Next: capture actor positions/slot distances and close native stairs/vehicles, fix confirmed issues narrowly, validate and report. No commit/push.\n'
for f in ['docs/DEAD_STREET_HIVE_MIND.md','docs/DEAD_STREET_JOURNAL.md']: (p/f).open('a',encoding='utf-8').write(event)
h=p/'docs/DEAD_STREET_HIVE_MIND.md'; lines=h.read_text(encoding='utf-8').splitlines(); lines=[('**Active objective (2026-09-15):** Native Harold cover-interaction correction, including vehicle crowding/overlap and stair-wall poses. Scarlet HQ Veloce owner-accepted. BUILD owns this scope; other chats retain UI/weapon-card work. See cover-interactions-01.') if x.startswith('**Active objective (2026-09-15):**') else x for x in lines]; h.write_text('\n'.join(lines)+'\n',encoding='utf-8')
probe=(p/'tools/harold_scale_20260915/hq_red/check.gd').read_text().replace('res://tools/harold_scale_20260915/hq_red/','res://tools/cover_interactions_20260915/').replace('DEAD_STREET_Harold_Red_HQ_Car.png','before.png')
probe=probe.replace('\tquit(0 if errors.is_empty() else 1)',"\n\tvar actors=[]\n\tvar tight_pairs=[]\n\tfor p in b.participants.values():\n\t\tvar node=view.actor_presenter._unit_nodes[p.participant_id]\n\t\tvar sprite=node.get_node(\"body\")\n\t\tvar pos=p.battle_position\n\t\tactors.append({\"id\":p.participant_id,\"side\":p.side_id,\"position\":[pos.x,pos.y],\"draw_position\":[node.position.x,node.position.y],\"slot\":p.occupied_cover_slot_id,\"direction\":view.actor_presenter.unit_direction_id(p.participant_id),\"clip\":view.actor_presenter.unit_clip_id(p.participant_id),\"sprite_offset\":[sprite.offset.x,sprite.offset.y],\"facing\":str(p.movement_intent)})\n\t\tfor other in b.participants.values():\n\t\t\tif p.participant_id>=other.participant_id:continue\n\t\t\tvar distance=pos.distance_to(other.battle_position)\n\t\t\tif distance<2.2:tight_pairs.append({\"a\":p.participant_id,\"b\":other.participant_id,\"distance\":distance,\"slot_a\":p.occupied_cover_slot_id,\"slot_b\":other.occupied_cover_slot_id})\n\tFileAccess.open(out+\"actors.json\",FileAccess.WRITE).store_string(JSON.stringify({\"actors\":actors,\"tight_pairs\":tight_pairs},\"\\t\"))\n\tview.set_process(false)\n\tview._camera.zoom=Vector2.ONE*5.\n\tview._camera.position=Vector2(25*8,19*6)\n\tawait settle(.15)\n\troot.get_texture().get_image().save_png(out+\"stairs_close.png\")\n\tview._camera.position=Vector2(44*8,34*6)\n\tawait settle(.15)\n\troot.get_texture().get_image().save_png(out+\"vehicles_close.png\")\n\tquit(0 if errors.is_empty() else 1)\n")
(out/'probe.gd').write_text(probe,encoding='utf-8')
godot=r'C:\Users\brand\OneDrive\Documents\Godot\Godot_v4.7.2-stable_win64.exe'
with (out/'probe_stdout.log').open('w',encoding='utf-8') as log:
    child=subprocess.Popen([godot,'--path',str(p),'--log-file',str(out/'probe.log'),'--script','res://tools/cover_interactions_20260915/probe.gd'],cwd=p,stdout=log,stderr=subprocess.STDOUT); print('NATIVE_PID',child.pid,flush=True); print('EXIT',child.wait(timeout=180),flush=True)