from pathlib import Path
import base64,zlib,subprocess,hashlib,json,sys
sys.stdout.reconfigure(encoding='utf-8',errors='backslashreplace')
r=Path(__file__).resolve().parents[2]; out=Path(__file__).parent
files=['battle/geometry/harold_street_catalog.gd','gameplay/harold_street_art.gd','battle/vehicles/battle_arrival_service.gd','tools/dusk_review/bake_harold_frontage.gd','assets/art/harold_frontage/ground.png']
print(subprocess.check_output(['git','status','--short','--',*files],cwd=r,text=True))
assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r,text=True).strip()
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip()=='d262e8f43f34b889ce72b1705d0f4de36d7e40fd'
hashes={}
for f in files:
 p=r/f; b=out/'baseline'/f; b.parent.mkdir(parents=True,exist_ok=True); assert not b.exists(); data=p.read_bytes(); b.write_bytes(data); hashes[f]=hashlib.sha256(data).hexdigest()
(out/'baseline_hashes.json').write_text(json.dumps(hashes,indent=2))
(out/'check.gd').write_bytes(zlib.decompress(base64.b64decode('eJylV11v2zYUfbZ/BacnaVXpjzYB6s0P7doiG4ZlSIPuIQsEWqIdLrKokrSdbNh/37kkZcutU2xYgMQWde+5534z8sHJprIsMdLORiOndW1HVtaydLIqjGhWspiOp+fjV5OzUXkny/uiEU5tJV9VybDUjXXsgs1Za2StRZVGnIVwrpajldRr6czj6E4YXVeFdUZKV5TCiVqvCCKLGG909fgkzFbeqbKWNj4X8blYQKmw0mxVKftg7x6U+89gEkrHYMPlpimZ2TRpNhsO9IYwj+LUeVWKuhelZDjYCsPaO2ElaSzkUhuZMLVkyfPn+6eGXX7gK4rGuqpVI4sNjBfCrGyaMVlDNxFLJw3gjNaOW/UnwX1EZrSZqnTy8uU4Z5PxeJwNB2+VbWvx+AH0peE71VR6B2fgELTSvX4WqNlSNoTVj85KrCVBjISxshF1YeRWyR13tmySjCvEVTROCSfTLDISVVWUd6quUg+IY7ETiHxrdCmtLZYGmMEi8rJUK5j8AUGxfC3uZTqZgj5+bxIhV8omOUu2aqVq+hJObgEZNKHRFqqicIagJ/s3yKIo7+H1UpRO6YZktKn19iBSySWK/FhkLU3pgxs4ew84fDSuCIWRLgWSkEfqYBJFENToYJCIMV0ANEgEdRinbkkX7Js5azZ1Da9C57AL7wFbqge3QSlEAIr2HgNF59Ra+vpodCXT5Jqoo9DeePSPEPaKlKJYyCh3ZM4J8pDbe9UWTiOLonqkjAU274NNvkB8m5ji9MhkzhYZt5uSHATlgM18YCxZXHAXmRStQMlSTpzZyH0gpQ8eP+uqhFxw0ptNM/+k1mJF363YgnWzSqm1nsWGecaSQJrjTRebUpii1CAIY+PhAB3EjN5RD11wJKO1vkMH6DAc30xvKeYJlJIZpc+phvgNDijP5myCA4I26KcZu8LfKcBJfXKLV2RCuztpvjBCVvybm7G3QyrjWxjyAW6085BoGPSuxTebBunJbZZ7UgzTBn8TuBp0yecRPXawWfAlTpB5Nwi89WDG803R/9MXOTt/ic9xxmVT1hrtlRKBzhgaV1WSCQu02vWsZgc0ZQv5aYOMihaOPnh9Py/4Y85e8BfnBGbReMj2hJ8zP/COoQJQL09z39uJqGvmdrJG2bfC3AMAMhYhcgIzr+oSTMPXHpLbUtQXHBqoNNVi8Fi+FfVGxhwEay1HgIqu+rVVVPmwuWloCNWihDUi2faBMEW68HKKjJ8qcxjr5kgRT320fWMyek2FG1cFDDtsRttqsz+LsJHZtmt6JpqKbZ/gWWpDkWZ7sCfZEt09picWaheNQ3Oc9h33D+kiZ9scGF9YW2BjgTi5gZUs0uTgwgJ5yFkYZpk3N+gVM8FyqpB16zBJKL5WLJD/Slm5XiCpkceT5In9KahZTHvoRnLIb4xibdlszm5uw5motqIp+6enRpBnH2upFm04HPO4imnQ6Q0V2HU3VaF/b2nnljQdd1hjcq/5PdqJ+9Qt9oE89GJJQ9w348l15y02eve0MS9RydoJyKxVs0yX2MQuJaXne7IZG/ntjh+eMz4hxS4+HI2KjfZVPU4KPc8hFU37Yf4VeqfvTXE/dNem+Hh0Y+IxV1SF3j9CO+TvmPVJ6/DDsztyoksL6sSj/vslNP0fS6jUKG7XbaF95C06Js2+65VlPBrGdeIbec7+SjxUMvMfeeI7yiaz8Jkn0hht8Bw+82TfTYVvE3pDzZEniIvGDR3PIQx54rng4MCJLnlZfIEDdHilRHOQuPlMdDS97Um3r856olhc6Wfi3/JXZxk0Dj7vLRyObvoROVjp6Xg7PQWy9IVSZ6vfd8nsuA//Hg7eo19f+0sK1yiqE1cIygP/w+oGs60n/dvVj9fvkHZcoiX9P6KQ+p8+XP7Cw3e1fEyDbp787hIah60hosnF66vLn98WV+9+vby6ZgA9qUUKnzbKpWO674fk9kZeuNijl/8BdFF8Yw==')))
note='\n\n## 20260915-harold-scale-01 - Vehicle/street update started\nOwner requested Harold Apartments vehicle sizing and a wider street, with a native screenshot. Verified branch build/arsenal-checkpoint-20260911, HEAD d262e8f, empty index; baseline copies/hashes in tools/harold_scale_20260915/. Shared fleet/bridge standard is1.6x; Harold parked cars still use old dimensions. Apply shared scale to all twelve parked cars and matching physical cover, widen road from12 to20 world units toward south, move lower sidewalk/building strip/lamps/litter together; preserve north frontage and unit scale. Arrival deployment bounds follow widened road. Scope: Harold catalog/art, Harold-only arrival service bounds, ground baker/cache and evidence. Concurrent music/portrait/range sources untouched. Next: native before sample, update/rebake, check clearances and native after screenshot. Existing publication blocker remains separate.\n'
for f in ['docs/DEAD_STREET_HIVE_MIND.md','docs/DEAD_STREET_JOURNAL.md']:
 with (r/f).open('a',encoding='utf-8') as h:h.write(note)
engine=Path(r.parent/'Godot/Godot_v4.7.2-stable_win64_console.exe')
with (out/'before.log').open('w',encoding='utf-8') as log:
 result=subprocess.run([str(engine),'--path',str(r),'--script','res://tools/harold_scale_20260915/check.gd','--position','20,30','--','--before'],stdout=log,stderr=subprocess.STDOUT,timeout=150)
print('BEFORE_EXIT',result.returncode);print((out/'before.log').read_text(encoding='utf-8')[-6000:])