from pathlib import Path
import subprocess,json,hashlib,shutil,zipfile,re
r=Path('C:/Users/brand/OneDrive/Documents/dead-street');out=r/'tools/whittaker_estate';d=out/'siren_cards_20260914';d.mkdir(exist_ok=True)
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip()=='77874acc264fe3318583780bf48b0776a3eba499'
paths=['gameplay/tactical_convoy_audio.gd','gameplay/tactical_battle_presentation.gd','tools/tactical_controls/estate_record.gd','tools/whittaker_estate/encode.py']
with zipfile.ZipFile(d/'before_sources.zip','w') as z:
 for rel in paths:z.write(r/rel,rel)
protected={str(p.relative_to(r)):hashlib.sha256(p.read_bytes()).hexdigest() for directory in ['battle','gameplay'] for p in (r/directory).rglob('*.gd') if str(p.relative_to(r)).replace('\\','/') not in paths};p=r/'tools/tactical_controls/estate_director.gd';protected[str(p.relative_to(r))]=hashlib.sha256(p.read_bytes()).hexdigest();(d/'protected_sources.json').write_text(json.dumps(protected,indent=2))
p=r/'docs/DEAD_STREET_JOURNAL.md';s=p.read_text(encoding='utf-8');s+='\n\n## 20260914-siren-cards-01 - Owner accepts battle; narrow presentation corrections\n\nBrandon: this battle is amazing; nothing should change except siren pace and combat loudness. Version-3 battle, layout, arrival, units, cover/flank, HUD, vehicle placement and ending are OWNER-ACCEPTED. Half-speed siren is too slow/drawn out and too loud during combat. Set pitch_scale to 0.75, midpoint between original 1.0 and current 0.5; increase TRC-only combat reduction from 6 to 18 dB (12 dB quieter than v3), preserving arrival gain, engines, Whittaker music and other emitters.\n\nAdditional standing owner rule: survivors appear first in both final result card stacks, across every battle. Living wounded count as survivors. Preserve weapon-class grouping within alive/dead groups, then stable participant-ID order. No combat or unit-state changes. Existing export gates will verify actual order and combat siren gain; a new recording will preserve the accepted configuration. No broad gameplay/performance retesting or other design edits.\n';p.write_text(s,encoding='utf-8')
p=r/'docs/DEAD_STREET_HIVE_MIND.md';s=p.read_text(encoding='utf-8');s=re.sub(r'\*\*Active objective:\*\*.*','**Active objective:** Brandon OWNER-ACCEPTED the version-3 battle. Narrow authorized changes only: TRC siren at 0.75 speed and 12 dB quieter during combat; all final result stacks put survivors (including wounded) ahead of dead units. Active chat owns this presentation pass; see journal siren-cards-01.',s);s=re.sub(r'\*\*Immediate next task:\*\*.*','**Immediate next task:** Capture and validate the accepted battle with only siren tuning and survivor-first result cards, then publish the bounded checkpoint. Preserve all other battle behavior and unrelated work.',s);p.write_text(s,encoding='utf-8')
p=r/'gameplay/tactical_convoy_audio.gd';s=p.read_text();assert s.count('player.pitch_scale=.5 if identity=="trc" else 1.')==1 and s.count('player.volume_db=-13.5-6.0*clampf(battle_mix,0.,1.)')==1;s=s.replace('player.pitch_scale=.5 if identity=="trc" else 1.','player.pitch_scale=.75 if identity=="trc" else 1.').replace('player.volume_db=-13.5-6.0*clampf(battle_mix,0.,1.)','player.volume_db=-13.5-18.0*clampf(battle_mix,0.,1.)');p.write_text(s)
p=r/'gameplay/tactical_battle_presentation.gd';s=p.read_text();old='  units.sort_custom(func(a,b):return ROLES.find(a.weapon_type)<ROLES.find(b.weapon_type))';assert s.count(old)==1;s=s.replace(old,'  units.sort_custom(func(a,b):\n   if a.is_alive!=b.is_alive:return a.is_alive\n   var left=ROLES.find(a.weapon_type);var right=ROLES.find(b.weapon_type)\n   return left<right if left!=right else a.participant_id<b.participant_id\n  )');p.write_text(s)
p=r/'tools/tactical_controls/estate_record.gd';s=p.read_text();assert 'var sample_times=[6.0,10.5,11.5,13.0,20.0]' in s;s=s.replace('var sample_times=[6.0,10.5,11.5,13.0,20.0]','var sample_times=[6.0,10.5,11.5,13.0,20.0,25.0,30.0]');p.write_text(s)
p=r/'tools/whittaker_estate/encode.py';s=p.read_text().replace("all(x['pitch_scale']==.5 for x in record['horn_gain_samples'])","all(x['pitch_scale']==.75 for x in record['horn_gain_samples'])");needle="assert sum(p['flanker'] for p in passengers)==4";assert needle in s;s=s.replace(needle,needle+"\ncombat_siren=[x for x in record['horn_gain_samples'] if x['phase']=='active']\nassert combat_siren and all(x['gain_db']<=-31.49 for x in combat_siren)\nfor rows in record['results'].values():\n seen_dead=False\n for row in rows:\n  if row['state']=='DEAD':seen_dead=True\n  else:assert not seen_dead,'Survivor appears below casualties'");p.write_text(s)
archive=d/'prior_version3';archive.mkdir(exist_ok=True)
for name in ['estate_raw.avi','record.json','record_source_hashes.json','delivery.json','Dead_Street_Whittaker_Estate_Mobile.mp4','capture.log','transfer.json']:
 p=out/name
 if p.exists():
  assert not (archive/name).exists(),name
  shutil.move(str(p),str(archive/name)) if name=='estate_raw.avi' else shutil.copy2(p,archive/name)
print('SIREN_075_COMBAT_MINUS_18_SURVIVORS_FIRST_CAPTURE_STARTING',flush=True)
subprocess.run(['C:/Users/brand/AppData/Local/DeadStreetTools/python/python.exe',str(out/'record_worker.py')],cwd=r,check=True,timeout=900)
