from pathlib import Path
import json,subprocess,hashlib,zipfile
r=Path(r'C:\Users\brand\OneDrive\Documents\dead-street');out=r/'tools/whittaker_estate/width_scenery_20260914';out.mkdir(exist_ok=True)
assert subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r).strip()==b''
files=['gameplay/tactical_command_hud.gd','gameplay/whittaker_estate_art.gd','tools/tactical_controls/estate_bake.gd','tools/tactical_controls/hud_layout_review.gd','assets/art/whittaker_estate/ground.png']
assert not (out/'before_sources.zip').exists()
with zipfile.ZipFile(out/'before_sources.zip','w') as z:
 for rel in files:z.write(r/rel,rel)
(out/'protected_sources.json').write_text(json.dumps({p.relative_to(r).as_posix():hashlib.sha256(p.read_bytes()).hexdigest() for folder in ['gameplay','battle','tools/tactical_controls'] for p in (r/folder).rglob('*.gd') if p.relative_to(r).as_posix() not in files},indent=2),encoding='utf-8')
journal=r/'docs/DEAD_STREET_JOURNAL.md'
with journal.open('a',encoding='utf-8') as f:f.write("\n\n## 20260914-width-scenery-01 - Owner presentation refinement\n\nSource: Brandon requests the estate driveway stop flush at the public road; bridge-like near-full-screen HUD width shared across maps, retaining the accepted compact height; develop the noncombat surroundings visible above the estate during the intro without changing zoom. This supersedes the fixed logical HUD width used in the height correction, not its height/card rules. Battle behavior, geometry, arrivals, cover, units, siren and result sorting remain locked. Verified HEAD 555d692 on the established build branch; index empty, unrelated dirty work and parallel private sandbox walkthrough preserved. Build chat owns this estate/HUD presentation pass. Exact gap found: the driveway's grown border reaches road x131, and the ground bake begins at (-512,-384), visibly clipping scenery/road in the unchanged intro. Plan: horizontally flexible HUD at existing uniform text/card scale; flush driveway border; extended baked contextual landscape with no new playable objects. Validation pending: shared HUD sizing, native intro/driveway inspection and one deterministic capture comparison.\n")
p=r/'docs/DEAD_STREET_HIVE_MIND.md';s=p.read_text(encoding='utf-8');a=s.index('**Active objective:**');b=s.index('\n\n',a);s=s[:a]+'**Active objective:** BUILD chat implementing owner-requested driveway/road seam, shared near-full-screen HUD width at existing compact height, and developed estate intro surroundings. Camera zoom and accepted battle remain unchanged. See journal width-scenery-01. Parallel sandbox UI review retains its private capture scope.'+s[b:]
a=s.index('**Immediate next task:**');b=s.index('\n\n',a);s=s[:a]+'**Immediate next task:** Apply the three presentation refinements, bake static scenery, verify bridge/estate HUD dimensions and native intro, then record and compare the accepted deterministic battle. Preserve all unrelated work and parallel walkthrough files.'+s[b:];p.write_text(s,encoding='utf-8')
print('WIDTH_SCENERY_SCOPE_RECORDED',len(files),flush=True)