from pathlib import Path
import json,subprocess,sys,hashlib,shutil
r=Path(r'C:\Users\brand\OneDrive\Documents\dead-street');out=r/'tools/whittaker_estate';o=out/'width_scenery_20260914';h=json.loads((o/'hud_layout.json').read_text());assert h['checks']==834 and not h['errors']
protected=json.loads((o/'protected_sources.json').read_text());changed=[p for p,v in protected.items() if hashlib.sha256((r/p).read_bytes()).hexdigest()!=v];assert not changed,changed
prior=o/'prior_version4';assert not prior.exists();prior.mkdir()
for name in ['estate_raw.avi','Dead_Street_Whittaker_Estate_Mobile.mp4','record.json','record_source_hashes.json','delivery.json','transfer.json','intro_full.png','opening_cover.png','arrival.png','combat_12.png','combat_30.png','aftermath.png','results.png']:
 if (out/name).exists():shutil.move(str(out/name),str(prior/name))
note='\n\n## 20260914-width-scenery-02 - Presentation checked; final capture\n\nIMPLEMENTED and native-checked. HUD expands horizontally with 12 logical-unit outer insets while retaining the height-limited 226-unit panel, original text scale and 46-unit two-row cards. Bridge and estate match at all three tested viewports; 834 layout/containment/state checks pass. First screenshot review found a new zero-sized header container rendered inconsistently on the bridge despite valid child bounds; removed that container and positioned the original surface children directly. Fresh native screenshot now visibly includes emblem, name, divider and strength on both maps. Scenery bake expands from 3072x1536 at (-512,-384) to 4096x2304 at (-1200,-900), with continuous road, fields, minor lane, utility poles, neighboring lots/buildings and tree belts. Driveway outer border starts exactly at road edge x139. Native intro and driveway inspected. All protected battle/gameplay/director sources unchanged, including camera/audio/result sorting; no geometry or combat edits. Version-4 capture artifacts preserved under width_scenery_20260914/prior_version4. One full capture follows; battle comparison, export and publication remain pending. Historical performance gap is not remeasured by offline capture.\n'
with (r/'docs/DEAD_STREET_JOURNAL.md').open('a',encoding='utf-8') as f:f.write(note)
p=r/'docs/DEAD_STREET_HIVE_MIND.md';s=p.read_text(encoding='utf-8');a=s.index('**Immediate next task:**');b=s.index('\n\n',a);s=s[:a]+'**Immediate next task:** Native layout and intro inspection passed; final estate recording and deterministic comparison are running. Then save the revised video and publish this scoped presentation checkpoint. See journal width-scenery-02.'+s[b:];p.write_text(s,encoding='utf-8')
print('PRESENTATION_VALIDATED_CAPTURE_START',len(protected),flush=True)
subprocess.run([sys.executable,str(out/'record_worker.py')],cwd=r,check=True)