import pathlib,json,hashlib,subprocess
p=pathlib.Path(r'C:\Users\brand\OneDrive\Documents\dead-street'); out=p/'tools/cover_interactions_20260915'; base=json.loads((out/'baseline.json').read_text())
owned=['battle/geometry/harold_street_catalog.gd','battle/presentation/tactical_participant_visual.gd','gameplay/tactical_battle_view.gd','battle/vehicles/battle_arrival_service.gd']
for f in owned: assert hashlib.sha256((p/f).read_bytes()).hexdigest()==base['sources'][f],f
event='\n\n## 20260915-cover-interactions-02 - Confirmed overlap causes; narrow correction\nNative snapshot records4 same-side arrival-door occupant pairs only1.4196/1.6068 world units apart. Harold static cover uses .85-world standoff and3.2px facing-dependent sprite translation, leaving only .45-world horizontal clearance when facing the cover; the stair defender occupies the inside corner only .15 before the wall end. Correct Harold only: keep displayed foot origins on physical points (remove forward nudge), use1.35-world static car/stoop standoff, move stair side slots .35 beyond the front corner, and reject arrival-door slots within2.4 world units of another door slot while suppressing conflicting unowned body slots. Physical doors remain intact; other maps retain existing rules. No unit art, size, collision checks or combat damage/LOS rules weakened. Baseline native record in actors.json/before.png. Initial supposed close captures remained at overview due camera controller; those filenames are not proof of zoomed inspection. Next: focused geometry/pose checks, actual close capture,20-second movement/combat review and bridge/estate preservation smoke.\n'
for f in ['docs/DEAD_STREET_HIVE_MIND.md','docs/DEAD_STREET_JOURNAL.md']: (p/f).open('a',encoding='utf-8').write(event)
f=p/owned[0]; t=f.read_text(); t=t.replace('var points=[[Vector2(center.x,b.position.y-.85)', 'var stand=1.35 if kind in ["car","stoop_wall"] else .85\n\t\tvar points=[[Vector2(center.x,b.position.y-stand)').replace('Vector2(center.x,b.end.y+.85)','Vector2(center.x,b.end.y+stand)').replace('Vector2(b.position.x-.85,center.y)','Vector2(b.position.x-stand,center.y)').replace('Vector2(b.end.x+.85,center.y)','Vector2(b.end.x+stand,center.y)').replace('points[2][0].y=b.end.y-.15','points[2][0].y=b.end.y+.35').replace('points[3][0].y=b.end.y-.15','points[3][0].y=b.end.y+.35'); f.write_text(t)
f=p/owned[1]; t=f.read_text(); old='\t\tview_pos.y *= 0.75\n\tif not participant.has_occupied_cover_slot():'; new='\t\tview_pos.y *= 0.75\n\t# Harold cover positions include body clearance; aiming must not slide feet into scenery.\n\tif battle_state != null and battle_state.battlefield_geometry != null and battle_state.battlefield_geometry.authored_layout_id == "dead_street_dusk_v1":\n\t\treturn view_pos\n\tif not participant.has_occupied_cover_slot():'; assert t.count(old)==1; f.write_text(t.replace(old,new))
f=p/owned[2]; t=f.read_text(); old='\tvar view_pos: Vector2 = _to_view(participant.battle_position)\n\tif not participant.has_occupied_cover_slot():'; new='\tvar view_pos: Vector2 = _to_view(participant.battle_position)\n\tif battle_state.battlefield_geometry.authored_layout_id == "dead_street_dusk_v1":\n\t\treturn view_pos\n\tif not participant.has_occupied_cover_slot():'; assert t.count(old)==1; f.write_text(t.replace(old,new))
f=p/owned[3]; t=f.read_text(); old='  g.add_cover_object(CoverObject.new(spec.id,spec.id))'; new='  if g.authored_layout_id==Catalog.ID and not _reserve_door_space(b,spec):continue\n'+old; assert t.count(old)==1; t=t.replace(old,new)
helper='\nstatic func _reserve_door_space(b,spec) -> bool:\n # A single usable firing position per tight door cluster, not stacked people.\n var g=b.battlefield_geometry;var hidden=[]\n for slot in g.cover_slots.values():\n  if slot.position.distance_squared_to(spec.slot)>=2.4*2.4:continue\n  if slot.is_occupied() or slot.is_reserved():return false\n  if "__door_" in slot.cover_object_id:return false\n  if "__body_cover" in slot.cover_object_id:hidden.append(slot)\n for slot in hidden:\n  b.vehicle_hidden_cover_slots[slot.cover_slot_id]=slot\n  g.remove_cover_slot(slot.cover_slot_id)\n return true\n'
f.write_text(t+helper)
probe=(out/'probe.gd').read_text().replace('before.png','after.png').replace('out+"actors.json"','out+"after_actors.json"').replace('out+"stairs_close.png"','out+"after_stairs_close.png"').replace('out+"vehicles_close.png"','out+"after_vehicles_close.png"'); (out/'after_probe.gd').write_text(probe)
godot=r'C:\Users\brand\OneDrive\Documents\Godot\Godot_v4.7.2-stable_win64.exe'
with (out/'after_stdout.log').open('w',encoding='utf-8') as log:
    child=subprocess.Popen([godot,'--path',str(p),'--log-file',str(out/'after.log'),'--script','res://tools/cover_interactions_20260915/after_probe.gd'],cwd=p,stdout=log,stderr=subprocess.STDOUT); print('PID',child.pid,flush=True); print('EXIT',child.wait(timeout=180),flush=True)