import pathlib,subprocess
p=pathlib.Path(r'C:\Users\brand\OneDrive\Documents\dead-street'); out=p/'tools/cover_interactions_20260915'
t=(p/'tools/harold_scale_20260915/check.gd').read_text().replace('res://tools/harold_scale_20260915/','res://tools/cover_interactions_20260915/validation/'); t=t.replace('\tvar frame_ms := []',"\n\tvar minimum=INF\n\tvar all_slots=b.battlefield_geometry.cover_slots.values()\n\tfor i in range(all_slots.size()):\n\t\tfor j in range(i+1,all_slots.size()):\n\t\t\tminimum=minf(minimum,all_slots[i].position.distance_to(all_slots[j].position))\n\tcheck(minimum>=2.399,\"all Harold cover positions have silhouette clearance\")\n\tfor p in b.participants.values():\n\t\tcheck(view.actor_presenter.unit_view_position(p.participant_id).is_equal_approx(p.battle_position*Vector2(8,6)),\"drawn foot matches physical origin \"+p.participant_id)\n"+'\tvar frame_ms := []'); (out/'validation').mkdir(exist_ok=True); (out/'validation/check.gd').write_text(t)
t=(p/'tools/harold_scale_20260915/check_other_maps.gd').read_text().replace('res://tools/harold_scale_20260915/other_maps_report.json','res://tools/cover_interactions_20260915/validation/other_maps_report.json'); t=t.replace('\t\tscene.queue_free();await process_frame',"\n\t\tvar legacy=load(\"res://tools/cover_interactions_20260915/before/tactical_participant_visual.gd\")\n\t\tvar legacy_doors=load(\"res://tools/cover_interactions_20260915/before/battle_arrival_service.gd\")\n\t\tfor p in b.participants.values():\n\t\t\tcheck(preload(\"res://battle/presentation/tactical_participant_visual.gd\").view_origin(b,p,8.).is_equal_approx(legacy.view_origin(b,p,8.)),map_id+\" unchanged unit origin \"+p.participant_id)\n\t\tfor v in b.vehicles.values():\n\t\t\tcheck(var_to_str(preload(\"res://battle/vehicles/battle_arrival_service.gd\").door_specs(v))==var_to_str(legacy_doors.door_specs(v)),map_id+\" unchanged door geometry \"+v.battle_vehicle_id)\n"+'\t\tscene.queue_free();await process_frame'); (out/'validation/other_maps.gd').write_text(t)
godot=r'C:\Users\brand\OneDrive\Documents\Godot\Godot_v4.7.2-stable_win64.exe'
for name in ['check','other_maps']:
 print('START',name,flush=True)
 with (out/'validation'/(name+'_stdout.log')).open('w',encoding='utf-8') as log:
  child=subprocess.Popen([godot,'--path',str(p),'--log-file',str(out/'validation'/(name+'.log')),'--script','res://tools/cover_interactions_20260915/validation/'+name+'.gd'],cwd=p,stdout=log,stderr=subprocess.STDOUT);print('PID',child.pid,flush=True);code=child.wait(timeout=240)
 print('END',name,code,flush=True);assert code==0