from pathlib import Path
import json
r=Path(r'C:\Users\brand\OneDrive\Documents\dead-street');o=r/'tools/yard_finish_20260915'
entry="\n### 20260915-doble-ocho-12 — final sidewalk/audio video delivered\n- Completed owner correction: gray slab sidewalks with visible spaced joints; incoming Ravicci Bond radio dominates arrival, defender building sits behind it. Fade returns to prior combat settings before battle. Reusable yard works with any attacker; video keeps the requested Ravicci win.\n- Same native battle verified exactly versus prior Ravicci record: winner, three survivors,23.90s combat, orders, manifest and all result-card fields identical. Camera1342samples/0violations; arrival/outro/errors all empty.246unrelated production GDScripts unchanged against248baseline;251captured source/art/config hashes unchanged. HEAD9604323afae49ee63915b378048cfac9940f1f66, index empty, no commit/push this pass.\n- Corrected audio probe uses initialized Doble Ocho view and native movie-maker audio; actual per-radio RMS attacker lead23.34/25.02/26.10/26.92dB at2.5/4.5/7/9.5s. Combat gain/range/attenuation preservation passes. Gray concrete and seams inspected in final encoded frame. Six known ObjectDB shutdown leaks; no final script errors. No broader regression claim.\n- Final53.7967s MP4,1280x720/30fps H264/AAC fast-start,7369078bytes,full decode pass,audio peak0.446738. SHA256 b31c1092b7bc3c7330a00d9370d4f1d5197050b8f103653b3efc4d627d74c413. Saved video libfile_e00f8e02fe808191bafc7466b9aa68be v0; screenshot libfile_fe89df92fa588191b1d47f6f76e3d26f v0.\n- Deliverable now DEAD_STREET_Ravicci_Raid_Final.mp4 (supersedes previous video's sidewalk/mix only). Remote evidence/repro: tools/yard_finish_20260915/. Next: owner review/play; no further map/battle changes requested. Preserve all mixed work and separate Harold cover/stair review. This final file is available directly for phone playback.\n"
readme="# Doble Ocho final sidewalk/audio correction — 2026-09-15\n\nImplemented and native-validated; owner review next. Latest event doble-ocho-12.\n\nGray neutral sidewalks and six-unit slab seams, gray curbs/aprons. Production edits only gameplay/doble_ocho_art.gd and gameplay/tactical_convoy_audio.gd plus rebaked assets/art/doble_ocho/ground.png. Previous geometry, cover, fleet and battle configuration unchanged.\n\nArrival focus: incoming radio+3dB plus retained10% boost,2600reach,.35attenuation; defender radio-14dB. Blends out with existing final-two-arrival-seconds transition. Combat gain/range/attenuation and victory foreground preserved. Actual native radio-bus capture gives23.34–26.92dB attacker lead at four sampled arrival positions. See audio_review.json/audio_review.gd. Initial silent/uninitialized probes were corrected and are not evidence; final probe waits for the authored view, enables audio and uses movie-maker rendering.\n\nFinal video: DEAD_STREET_Ravicci_Raid_Final.mp4;53.7967seconds,1280x720/30fps H264/AAC fast-start,7369078bytes. Native recording1152x648, export upscale1280x720. Fully decoded and finite audio peak.446738. SHA256 b31c1092b7bc3c7330a00d9370d4f1d5197050b8f103653b3efc4d627d74c413.\nVideo libfile_e00f8e02fe808191bafc7466b9aa68be v0; screenshot libfile_fe89df92fa588191b1d47f6f76e3d26f v0. Chat files /workspace/scratch/6a4bd31e258d/yard_finish/DEAD_STREET_Ravicci_Raid_Final.mp4 and DEAD_STREET_Gray_Sidewalks.png.\n\nSame Ravicci7vCalleOcho7 showcase as previous: T3vsT2 stock weapons, Monarch4/Obsidian3, seed91517. Verify_delivery.py confirms exact winner/survivors23.90s combat/orders/manifest/results equality. Three Ravicci survivors; no health/damage/RNG/winner overrides.0camera violations over1342samples;0arrival/outro/errors. Six existing ObjectDB shutdown leaks; no full regression claim.\n\nPreservation.json:246other production scripts match248file baseline;251capture hashes intact. HEAD9604323afae49ee63915b378048cfac9940f1f66; index empty. No commit/push. Preserve earlier mixed work. Exact backups before/ and baseline.json. Prior map geometry/integration checks remain in tools/yard_revision_20260915/; only the current correction was rerun here.\n\nReproduce: run_native.py bake for scenery; run_native.py audio audio_review.gd for mixer proof; record_worker.py for same native battle/encode. Preserve existing raw video by cloning capture tools into a new take directory and adjusting paths before recapturing. Source changes are live through Sandbox shortcut. Production reusable preset remains Sierra Roja; capture_config.gd defines the owner-requested Ravicci video cast. Next owner review; Harold cover/stairs remains separate.\n"
for name in ['DEAD_STREET_HIVE_MIND.md','DEAD_STREET_JOURNAL.md','DEAD_STREET_PROJECT_CONTROL.md']:
 p=r/'docs'/name;s=p.read_text(encoding='utf-8')
 if '### 20260915-doble-ocho-12' not in s:s+=entry
 if name=='DEAD_STREET_HIVE_MIND.md':
  updates={'**Active objective (2026-09-15):**':'**Active objective (2026-09-15):** Doble Ocho gray sidewalk/slab and arrival-radio correction complete; final Ravicci victory MP4 delivered. Owner review/play next. See doble-ocho-12 and tools/yard_finish_20260915/README.md. Preserve concurrent menu work and separate Harold cover/stair review.','**Immediate next task:**':'**Immediate next task:** Owner reviews DEAD_STREET_Ravicci_Raid_Final.mp4 and current live-source Doble Ocho. Resume from tools/yard_finish_20260915/README.md; prior map/battle is preserved exactly, current sidewalk and arrival mix supersede older videos.','| BUILD / fourth map |':'| BUILD / fourth map | Doble Ocho final sidewalks/audio and Ravicci video | Complete / native-validated / owner review. Gray slab sidewalks; Ravicci radio leads arrival; exact previous Ravicci battle retained. See doble-ocho-12 and tools/yard_finish_20260915/README.md. Uncommitted/unpushed; preserve mixed work. |'}
  for prefix,new in updates.items():
   matches=[line for line in s.splitlines() if line.startswith(prefix)];assert len(matches)==1,prefix;s=s.replace(matches[0],new)
 p.write_text(s,encoding='utf-8')
(o/'README.md').write_text(readme,encoding='utf-8')
(o/'library_receipts.json').write_text("{\"results\":[{\"current_version_number\":0,\"file_id\":\"file_000000007de88246816b6c0d171144a0\",\"file_name\":\"DEAD_STREET_Ravicci_Raid_Final.mp4\",\"library_file_id\":\"libfile_e00f8e02fe808191bafc7466b9aa68be\",\"local_metadata_applied\":true,\"local_path\":\"/workspace/scratch/6a4bd31e258d/yard_finish/DEAD_STREET_Ravicci_Raid_Final.mp4\",\"path\":\"/Dead Street/DEAD_STREET_Ravicci_Raid_Final.mp4\",\"purpose\":\"create_library_file\",\"status\":\"succeeded\"},{\"current_version_number\":0,\"file_id\":\"file_00000000d43881f8bffe3b9d6823c3bd\",\"file_name\":\"DEAD_STREET_Gray_Sidewalks.png\",\"library_file_id\":\"libfile_fe89df92fa588191b1d47f6f76e3d26f\",\"local_metadata_applied\":true,\"local_path\":\"/workspace/scratch/6a4bd31e258d/yard_finish/DEAD_STREET_Gray_Sidewalks.png\",\"path\":\"/Dead Street/DEAD_STREET_Gray_Sidewalks.png\",\"purpose\":\"create_library_file\",\"status\":\"succeeded\"}]}",encoding='utf-8')
print('FINAL_HIVE_JOURNAL_CONTROL_AND_HANDOFF_SAVED')
