from pathlib import Path
import subprocess,json
r=Path('C:/Users/brand/OneDrive/Documents/dead-street');d=r/'tools/tactical_controls/hud_fixed_20260914'
p=r/'battle/geometry/whittaker_estate_catalog.gd';s=p.read_text();assert '[116.,74.,"rancher"' in s;s=s.replace('[116.,74.,"rancher"','[119.,88.,"rancher"');p.write_text(s)
p=r/'gameplay/estate_battle_setup.gd';s=p.read_text();s=s.replace('   for pose in candidates:\n','   var vehicle_candidates=[[Vector2(116,74),Vector2.LEFT]]+candidates if side_id==b.defender_side_id and v.vehicle_type_id=="workhorse" else candidates\n   for pose in vehicle_candidates:\n');p.write_text(s)
p=r/'tools/tactical_controls/estate_assault_checks.gd';s=p.read_text();s=s.replace(' var report={"passenger_manifests"',' var residents=[]\n for v in b.vehicles.values():\n  if v.side_id!=b.defender_side_id:continue\n  residents.append({"vehicle":v.vehicle_type_id,"position":str(v.battle_position)})\n  if v.vehicle_type_id=="workhorse":check(v.battle_position.is_equal_approx(Vector2(116,74)),"white Workhorse relocated onto paved circle")\n var report={"resident_vehicles":residents,"passenger_manifests"');p.write_text(s)
p=r/'tools/tactical_controls/estate_record.gd';s=p.read_text();s=s.replace('var safety_errors=[]','var safety_errors=[]\nvar entered_objective={}');old='  if p.stage=="ending" and not node.visible and safety_errors.size()<20:safety_errors.append("Hidden survivor "+id)';new='  if p.stage=="ending" and not node.visible:\n   var route=p.outro.routes.get(id,{})\n   var valid_entry=route.get("action","")=="enter" and p.end_clock>=float(route.get("start",INF))+float(route.get("travel",INF))+.6 and node.position.distance_to(route.points[-1]*Vector2(8,6))<.1\n   if valid_entry:entered_objective[id]=true\n   elif safety_errors.size()<20:safety_errors.append("Hidden survivor "+id)';assert old in s;s=s.replace(old,new).replace('var report={"arrival_manifest"','var report={"entered_objective":entered_objective.keys(),"arrival_manifest"');s=s.replace('quit(0 if b.battle_phase=="resolved" else 1)','quit(0 if b.battle_phase=="resolved" and safety_errors.is_empty() and p.outro.errors.is_empty() and p.last_path_errors.is_empty() else 1)');p.write_text(s)
for rel in ['tools/whittaker_estate/record_worker.py','tools/whittaker_estate/encode.py']:
 p=r/rel;s=p.read_text();s=s.replace("probe['winner']=='defender'","probe['winner'] in ['attacker','defender']").replace("record['winner']=='defender'","record['winner'] in ['attacker','defender']");p.write_text(s)
p=r/'docs/DEAD_STREET_JOURNAL.md';s=p.read_text(encoding='utf-8');s+='\n\n## 20260914-active-resume-14 - Native audit correction and exact truck identity\n\nNative resize run confirmed actual dismount counts 7/5/4, all 16 begin covered, four Vigil flankers, zero HUD overlap and TRC siren pitch 0.5. It resolved with TRC victory at 37.8 seconds, unlike the headless probe; final native capture is authoritative for its outcome. No forced defender winner: export gate now accepts either genuine resolved side. Native hidden-survivor check was defender-only: an attacker legally reached the mansion entrance and faded inside. Audit now accepts invisibility only for an enter-objective route after arrival/fade and within 0.1 rendered pixel of its real endpoint; any premature/unexplained disappearance still fails. Completion now returns failure for recorded presentation errors, not merely unresolved battles.\n\nVisual inspection corrected the vehicle identification: the offending upper truck in the trio is dynamic white Workhorse, not the neighboring static Rancher. Restored Rancher at 119,88; gave resident Workhorse preferred legal circle pose 116,74 and added exact-position check. This supersedes resume-12 identification. Native audit rerunning with the exact truck.\n';p.write_text(s,encoding='utf-8')
for label,args in [('pack',[str(r/'tools/tactical_controls/run.py'),'pack']),('assault',['--headless','--','--check=estate_assault_checks']),('audit',['--fixed-fps','30','--disable-vsync','--','--check=estate_audit'])]:
 exe='C:/Users/brand/AppData/Local/DeadStreetTools/python/python.exe' if label=='pack' else 'C:/Users/brand/AppData/Local/DeadStreetTools/godot_release_4.7.2/godot.exe'
 result=subprocess.run([exe]+args,cwd=r,capture_output=True,timeout=240);log=(result.stdout+result.stderr).decode(errors='replace');(d/(label+'_verified.log')).write_text(log);print(label,result.returncode,log[-2200:],flush=True);assert result.returncode==0 and 'SCRIPT ERROR' not in log and 'RECORD_ERROR' not in log
