from pathlib import Path
import subprocess,json
r=Path('C:/Users/brand/OneDrive/Documents/dead-street');d=r/'tools/tactical_controls/hud_fixed_20260914'
p=r/'tools/tactical_controls/estate_record.gd';s=p.read_text();s=s.replace('var radio_gain_samples=[]','var arrival_manifest=[]\nvar radio_gain_samples=[]');s=s.replace('  if presentation.stage=="ready" and presentation.ready_clock>.7:\n   var result=', '  if presentation.stage=="ready" and presentation.ready_clock>.7:\n   for vehicle in b.vehicles.values():\n    if vehicle.side_id!=b.attacker_side_id:continue\n    var passengers=[]\n    for unit in b.participants.values():\n     if unit.transport_vehicle_id!=vehicle.battle_vehicle_id:continue\n     var route=presentation.routes.get(unit.participant_id,{})\n     if route.is_empty():printerr("RECORD_ERROR missing passenger dismount");quit(1);return false\n     passengers.append({"id":unit.participant_id,"seat":unit.get_meta("transport_seat",-1),"route_start":str(route.points[0]),"route_end":str(route.points[-1]),"start_seconds":route.start,"covered":not unit.occupied_cover_slot_id.is_empty(),"flanker":unit.get_meta("estate_flanker",false)})\n    arrival_manifest.append({"vehicle":vehicle.vehicle_type_id,"count":passengers.size(),"passengers":passengers})\n   var result=');s=s.replace('var report={"result_camera_jump_pixels"','var report={"arrival_manifest":arrival_manifest,"result_camera_jump_pixels"');p.write_text(s)
for label,args in [('pack',[str(r/'tools/tactical_controls/run.py'),'pack']),('probe',['--headless','--','--check=estate_probe']),('audit',['--fixed-fps','30','--disable-vsync','--','--check=estate_audit'])]:
 exe='C:/Users/brand/AppData/Local/DeadStreetTools/python/python.exe' if label=='pack' else 'C:/Users/brand/AppData/Local/DeadStreetTools/godot_release_4.7.2/godot.exe'
 result=subprocess.run([exe]+args,cwd=r,capture_output=True,timeout=240);log=(result.stdout+result.stderr).decode(errors='replace');(d/(label+'_final.log')).write_text(log);print(label,result.returncode,log[-1200:],flush=True)
 assert result.returncode==0 and 'SCRIPT ERROR' not in log and 'RECORD_ERROR' not in log
 if label=='probe':
  report=json.loads((r/'tools/whittaker_estate/probe.json').read_text());print('PROBE_RESULT',report['phase'],report['winner'],report['duration'],flush=True);assert report['phase']=='resolved',report
