from pathlib import Path
import subprocess,json,hashlib,re,shutil
r=Path('C:/Users/brand/OneDrive/Documents/dead-street');out=r/'tools/whittaker_estate';d=r/'tools/tactical_controls/hud_fixed_20260914'
j=json.loads((out/'record.json').read_text());a=json.loads((d/'assault.json').read_text());h=json.loads((d/'hud_layout.json').read_text());v=json.loads((out/'transfer.json').read_text());hashes=json.loads((out/'record_source_hashes.json').read_text());assert all(hashlib.sha256((r/p).read_bytes()).hexdigest()==sha for p,sha in hashes.items())
assert not j['presentation_errors'] and not a['errors'] and not h['errors'] and v['decoded_to_end']
summary=f"""## Current owner-feedback correction - 2026-09-14
IMPLEMENTED / VALIDATED; Brandon's review pending. This section supersedes all older vocal, HUD, horn, arrival and truck placement statuses below.
All faction vocals are removed from active presentation and asset packaging. The premise, service and 36 clips remain recoverable under tools/parked_faction_voices; further voice-bank work is PARKED.
Every combat HUD uses the bridge's 226-unit panel at the 1152x800 reference scale. Sixteen cards fit in two condensed 46-unit rows without increasing panel height. Maximum screen-height share is 28.25%; matched bridge/estate viewports have identical HUD size.
TRC uses an original broken warning siren at pitch_scale 0.5 (half speed and lower pitch). Driving audio is unchanged. Quiet Whittaker porch music and victory foreground behavior remain.
The lower estate fence is complete, with a garage-aligned opening and visible outward-open leaves. Assault vehicles cut across grass and stop at different diagonal angles. All 16 TRC occupy real fence/gate or vehicle cover before combat. Actual dismounts verify Aegis 7, Watchdog 5, Vigil 4, unique seats and passenger IDs. All four Vigil passengers form the replaceable lower-gate flank; ordinary combat movement resumes after the gate goal. Casualties may interrupt it. The white resident Workhorse is at (116,74), visibly on the circle; neighboring Rancher restored.
Validation: {h['checks']} native HUD/card-state checks; {a['checks']} geometry/assault/passenger checks; existing native line controls 43/43. Final recording: {j['actor_frame_checks']} actor-frame checks, zero presentation/HUD/arrival/outro errors, zero camera violations, ending movement maximum {j['max_outro_jump_pixels']:.3f}px/frame, result-camera jump {j['result_camera_jump_pixels']}px. Runtime TRC pitch 0.5, zero faction vocals, all 16 equipped model labels and all passenger/cover counts verified.
Final native combat resolves naturally at {j['combat_seconds']:.2f}s, Whittaker victory with {j['result_summaries']['defender']['remaining']} survivors. No forced winner, health, RNG, victory-service or production-cap changes. Seed 9146 is a showcase fixture, not cross-mode determinism certification.
Delivered video: {v['seconds']:.3f}s, 1280x720/30fps H.264/AAC, {v['bytes']:,} bytes, full decode passed, stereo peak {v['audio_peak']:.3f}; SHA256 {v['sha256']}. Saved as version 3 of Dead_Street_Whittaker_Estate_Mobile.mp4 (libfile_5962de2d811081919c16f93b3f306b4c).
Evidence: record.json, record_source_hashes.json, delivery.json, opening_cover.png; owner_feedback_20260914/record.json for resize audit; hud_fixed_20260914/{{hud_layout,assault}}.json for focused checks. Previous video/raw metadata retained in owner_feedback_20260914/prior_version2. Reproduce with run.py pack and --check=estate_assault_checks / hud_layout_review / estate_audit; record_worker.py and encode.py gate the full movie. Never repack during capture.
Failed trials and fixes: journal active-resume-09 through -16. Zero-speed flank and apron hold were fixed in showcase order setup. An earlier defender-only audit incorrectly flagged a lawful attacker doorway entry; only verified endpoint entry is exempt, and all premature disappearance still fails. The initial Rancher identification was corrected to the exact Workhorse.
Remaining: owner visual/listening acceptance; historical estate 44.42 FPS sample remains unresolved and was not remeasured. Broader performance, final convoy/personnel caps and riot-shield proposal remain open. Faction vocals are parked, not unfinished integration. Preserve unrelated character-factory/dusk/source-recovery and battle_victory_service work. Source publication is recorded by Git and the local feedback checkpoint receipt; no recursive receipt commit is required.

"""
p=out/'README.md';old=p.read_text(encoding='utf-8');p.write_text(summary+'## Historical checkpoint (superseded by feedback above)\n\n'+old,encoding='utf-8')
p=r/'docs/DEAD_STREET_PROJECT_CONTROL.md';old=p.read_text(encoding='utf-8');p.write_text('# Current milestone - owner feedback applied - 2026-09-14\n\nIMPLEMENTED / VALIDATED; owner review pending. Vocals removed and parked; uniform bridge-sized HUD with condensed two-row cards; TRC broken siren at half speed, driving sound preserved; complete lower fence/open garage gate; angled assault parking and all attackers in real opening cover; exact 7/5/4 passengers with four-person Vigil flank; white Workhorse moved onto paved circle. Final 88.197-second version-3 video is fully decoded and saved. Native HUD 786 checks and existing native controls 43 checks pass; final record has zero HUD/presentation/route errors. See estate README and journal active-resume-16 for exact evidence and failures. Remaining: owner review, historical 44.42 FPS performance gap, global caps and shield proposal. All faction voice expansion is parked. Older conflicting statuses below are historical.\n\n'+old,encoding='utf-8')
p=r/'docs/DEAD_STREET_HIVE_MIND.md';s=p.read_text(encoding='utf-8');s=re.sub(r'\*\*Active objective:\*\*.*','**Active objective:** Owner feedback implemented and validated: vocals parked; bridge-sized HUD; half-speed broken TRC siren; complete lower fence/gate; covered assault arrival with exact 7/5/4 passengers and four-person Vigil flank; white Workhorse on circle. Version-3 video saved. Active build chat is finishing the scoped checkpoint; owner review next. See journal active-resume-16.',s);s=re.sub(r'\*\*Latest estate evidence:\*\*.*',f"**Latest estate evidence:** HUD {h['checks']} checks, assault/passengers {a['checks']} checks, native line controls 43. Final capture {j['actor_frame_checks']} actor-frame checks, zero HUD/hidden-survivor/route errors and zero result-camera jump. 88.197-second video version 3, native combat 48.30s, four Whittaker survivors. See estate report for bounded validation and failed trials.",s);s=re.sub(r'\*\*Immediate next task:\*\*.*','**Immediate next task:** Finish scoped source checkpoint/publication, then Brandon reviews version 3. Apply further feedback without reopening parked vocals or broad performance work. Consult Git and local feedback checkpoint receipt for exact publication state.',s);p.write_text(s,encoding='utf-8')
p=r/'docs/DEAD_STREET_JOURNAL.md';s=p.read_text(encoding='utf-8');s+='\n\n## 20260914-active-resume-16 - Final recording delivered and bounded validation complete\n\n'+summary.split('IMPLEMENTED / VALIDATED;',1)[1]+'\nCode/source hashes match the final recording snapshot. Video transfer hash verified independently and existing recording replaced as version 3. Technical success does not imply owner acceptance. Preparing only this feedback scope for commit/push under existing authorization; preserve every unrelated dirty/untracked item. No recursive receipt-only publication loop.\n';p.write_text(s,encoding='utf-8')
scope=['docs/DEAD_STREET_HIVE_MIND.md','docs/DEAD_STREET_JOURNAL.md','docs/DEAD_STREET_PROJECT_CONTROL.md','docs/TACTICAL_CONTROLS_2026-09-13.md','battle/geometry/whittaker_estate_catalog.gd','gameplay/estate_battle_setup.gd','gameplay/whittaker_estate_art.gd','gameplay/tactical_battle_presentation.gd','gameplay/tactical_command_hud.gd','gameplay/tactical_compact_card.gd','gameplay/tactical_convoy_audio.gd','gameplay/tactical_faction_voices.gd','assets/art/whittaker_estate/ground.png','assets/audio/convoy/trc_horn.wav','assets/audio/convoy/trc_siren.wav','assets/audio/convoy/trc_siren_manifest.json']
scope += ['tools/tactical_controls/'+x for x in ['estate_director.gd','estate_record.gd','estate_audit.gd','estate_assault_checks.gd','hud_layout_review.gd','run.py','hud_fixed_20260914/hud_layout.json','hud_fixed_20260914/assault.json']]
scope += ['tools/whittaker_estate/'+x for x in ['README.md','build_trc_siren.py','record_worker.py','encode.py','record.json','record_source_hashes.json','delivery.json','opening_cover.png','arrival.png','combat_12.png','combat_30.png','aftermath.png','results.png','owner_feedback_20260914/record.json']]
scope += [str(p.relative_to(r)).replace('\\','/') for p in (r/'tools/parked_faction_voices').rglob('*') if p.is_file()]
scope += subprocess.check_output(['git','ls-files','assets/audio/factions'],cwd=r,text=True).splitlines()
scope += ['assets/art/whittaker_estate/props/'+x for x in ['boundary_fence_100_102.png','boundary_fence_49_102.png','boundary_fence_49_9.png','service_gate_open_100.png','service_gate_open_80.png','service_gate_pier_100.png','service_gate_pier_80.png']]
scope=sorted(set(scope));(d/'feedback_scope.json').write_text(json.dumps(scope,indent=2));assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r,text=True).strip(),'Preexisting staged work; preserve it'
subprocess.run(['git','diff','--check','--']+scope,cwd=r,check=True,capture_output=True);subprocess.run(['git','add','-A','--']+scope,cwd=r,check=True,capture_output=True);staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r,text=True).splitlines();assert set(staged)<=set(scope)
print('SCOPED_STAGE',len(staged),'paths',a['checks'],'assault checks');print(subprocess.check_output(['git','diff','--cached','--stat'],cwd=r,text=True))
