from pathlib import Path
import subprocess
r=Path('C:/Users/brand/OneDrive/Documents/dead-street');d=r/'tools/tactical_controls/hud_fixed_20260914'
p=r/'tools/tactical_controls/estate_director.gd';s=p.read_text();s=s.replace('var flank_paths=[]','var flank_paths=[]\nvar flank_completed={}');s=s.replace('   if valid:p.set_player_move_intent()','   if valid:\n    p.set_movement_speed(preload("res://battle/combat/battle_combat_behavior_catalog.gd").DEFAULT_COMBAT_MOVEMENT_SPEED)\n    p.set_player_move_intent()');s=s.replace(' var t=b.elapsed_time_seconds\n for e in b.combat_feedback_events:', ' var t=b.elapsed_time_seconds\n for id in flank_ids:\n  if flank_completed.has(id):continue\n  var unit=b.get_participant(id)\n  if unit==null or not unit.is_alive or unit.is_wounded:continue\n  if unit.battle_position.y<101. and unit.battle_position.x>81.:\n   flank_completed[id]=true;log.append({"time":t,"event":"flanker_entered_gate","id":id,"position":str(unit.battle_position)})\n  if unit.current_player_intent()=="hold" and unit.current_player_group_command().is_empty() and unit.battle_position.y<101. and unit.has_player_order_position and unit.battle_position.distance_to(unit.player_order_position)<.8:\n   unit.clear_player_tactical_intent()\n for e in b.combat_feedback_events:');p.write_text(s)
p=r/'tools/tactical_controls/estate_assault_checks.gd';s=p.read_text();needle=' var dir=Director.new();dir.setup(b,null)';new=' var manifests=[];var passengers=[]\n for v in b.vehicles.values():\n  if v.side_id!=b.attacker_side_id:continue\n  var assigned=[];var seats=[]\n  for unit in b.participants.values():\n   if unit.transport_vehicle_id!=v.battle_vehicle_id:continue\n   assigned.append(unit.participant_id);seats.append(int(unit.get_meta("transport_seat",-1)))\n   check(unit.participant_id not in passengers,"passenger assigned only once "+unit.participant_id);passengers.append(unit.participant_id)\n   check(bool(unit.get_meta("estate_flanker",false))==(v.vehicle_type_id=="vigil"),"whole Vigil fireteam flanks "+unit.participant_id)\n  var expected={"aegis":7,"watchdog":5,"vigil":4}[v.vehicle_type_id]\n  assigned.sort();seats.sort();var declared=v.get_meta("convoy_occupants",[]);declared.sort()\n  check(assigned.size()==expected,"vehicle passenger count "+v.vehicle_type_id)\n  check(assigned==declared,"arrival manifest matches participants "+v.vehicle_type_id)\n  check(seats==range(expected),"unique consecutive seats "+v.vehicle_type_id)\n  manifests.append({"vehicle":v.vehicle_type_id,"count":assigned.size(),"seats":seats,"participants":assigned})\n check(passengers.size()==16,"all sixteen passengers accounted for")\n var dir=Director.new();dir.setup(b,null)';assert needle in s;s=s.replace(needle,new).replace('var report={"checks"','var report={"passenger_manifests":manifests,"checks"');p.write_text(s)
p=r/'docs/DEAD_STREET_JOURNAL.md';s=p.read_text(encoding='utf-8');s+='\n\n## 20260914-active-resume-12 - Passenger integrity, four-person flank and driveway truck\n\nBrandon requires correct real passenger counts per vehicle; four flankers are acceptable to keep the rear transport together. Configured convoy is Aegis 7, Watchdog 5, Vigil 4; all four Vigil passengers now flank. Explicit manifest/seat/unique participant checks added. The top vehicle in the trio east of the lower garage (parked Rancher at 119,88) moved to 116,74 on the paved circular driveway, avoiding the flower border.\n\nNative battle audit failed honestly at 180 simulation seconds: no result, no HUD overlap or arrival path errors. Headless diagnosis found flankers had valid external paths but inherited zero movement speed from covered deployment; order setup now initializes the standard combat movement speed. Added actual gate-entry events and release of completed showcase flank positioning back to ordinary assault AI. New simulation underway; do not call the previous cutoff a passing battle or alter casualties to force resolution.\n';p.write_text(s,encoding='utf-8')
for name,args in [('pack',[str(r/'tools/tactical_controls/run.py'),'pack']),('assault',['--headless','--','--check=estate_assault_checks']),('probe',['--headless','--','--check=estate_probe'])]:
 exe='C:/Users/brand/AppData/Local/DeadStreetTools/python/python.exe' if name=='pack' else 'C:/Users/brand/AppData/Local/DeadStreetTools/godot_release_4.7.2/godot.exe'
 result=subprocess.run([exe]+args,cwd=r,capture_output=True,timeout=180);log=(result.stdout+result.stderr).decode(errors='replace');(d/(name+'_moving.log')).write_text(log);print(name,result.returncode,log[-10000:] if name=='probe' or result.returncode else log[-250:],flush=True)
 assert result.returncode==0 and 'SCRIPT ERROR' not in log
