from pathlib import Path
import subprocess,json,re,datetime
r=Path('C:/Users/brand/OneDrive/Documents/dead-street');d=r/'tools/tactical_controls/hud_fixed_20260914'
head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip();remote=subprocess.check_output(['git','ls-remote','origin','refs/heads/build/arsenal-checkpoint-20260911'],cwd=r,text=True).split()[0]
assert head==remote=='77874acc264fe3318583780bf48b0776a3eba499'
receipt={'verified_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'head':head,'remote':remote,'branch':'build/arsenal-checkpoint-20260911','status':'pushed and remote verified','video_version':3,'video_sha256':'4b3925d681c7c22d11e97571d903e332909718b3f146c2b448cfd8d92519bfbe','next':'Owner reviews version 3; vocals remain parked; preserve unrelated work','receipt_policy':'Local completion note accompanies next substantive checkpoint; no recursive receipt commit'}
(d/'feedback_checkpoint_receipt.json').write_text(json.dumps(receipt,indent=2))
p=r/'docs/DEAD_STREET_HIVE_MIND.md';s=p.read_text(encoding='utf-8');s=s.replace('Published gameplay checkpoint: 15c6bbc1292c745408869e545d5ae9dab31991cc.','Published feedback checkpoint: '+head+'.').replace('Verified remote checkpoint: a493f38afd27802798d84159ee56ef3abc7221f7.','Verified remote checkpoint: '+remote+'.').replace('Approved source, handoff and completion receipt are published; owner video feedback next.','Owner feedback source, handoff and validation evidence are published; version-3 review next.').replace('Active build chat is finishing the scoped checkpoint; owner review next.','No build pass is running; owner review next.');s=re.sub(r'\*\*Checkpoint / publication:\*\*.*','**Checkpoint / publication:** PUSHED / VERIFIED 2026-09-14: '+head+' on origin/build/arsenal-checkpoint-20260911. Scoped feedback, handoffs and validation evidence published; video version 3 saved. Local receipt: tools/tactical_controls/hud_fixed_20260914/feedback_checkpoint_receipt.json. This post-push status note accompanies the next substantive checkpoint; do not create another receipt-only publication loop.',s);s=re.sub(r'\*\*Immediate next task:\*\*.*','**Immediate next task:** Brandon reviews version 3. Apply further feedback; vocals remain parked. Performance (historical 44.42 FPS sample), final global caps and shield proposal remain open. Source is pushed and verified; preserve unrelated dirty/untracked work.',s);p.write_text(s,encoding='utf-8')
p=r/'docs/DEAD_STREET_JOURNAL.md';s=p.read_text(encoding='utf-8');s+='\n\n## 20260914-active-resume-17 - Feedback checkpoint published\n\nCommitted and pushed '+head+' to the existing build branch; git ls-remote independently matches local HEAD. Scope: 84 files including preserved voice-bank renames, requested source changes, focused fixtures, evidence and handoff. Version-3 movie already saved and transfer hash verified. Unrelated work preserved; no build/capture process remains. Next: owner video review. This local receipt/status note accompanies the next substantive change, without a new receipt-only commit/push loop.\n';p.write_text(s,encoding='utf-8')
print('PUSH_VERIFIED',head);print('UNRELATED_TRACKED_WORK',subprocess.check_output(['git','status','--short','--untracked-files=no'],cwd=r,text=True));print('INDEX_EMPTY',not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r,text=True).strip())
