from pathlib import Path
import subprocess,json,hashlib,re
r=Path('C:/Users/brand/OneDrive/Documents/dead-street');out=r/'tools/whittaker_estate';d=out/'siren_cards_20260914';v=json.loads((out/'transfer.json').read_text());check=json.loads((d/'verification.json').read_text());j=json.loads((out/'record.json').read_text())
assert all(check['approved_battle_comparison'].values()) and v['decoded_to_end'] and not j['presentation_errors']
protected=json.loads((d/'protected_sources.json').read_text());assert all(hashlib.sha256((r/k).read_bytes()).hexdigest()==sha for k,sha in protected.items())
note=f"""VALIDATED / delivered as video version 4. TRC siren pitch 0.75; arrival gain stays -13.5 dB, full combat base is -31.5 dB before existing shot ducking (12 dB quieter than version 3). Observed active-combat samples were -33.5 and -33.167 dB. Both final stacks are survivor-first; the Whittaker stack begins ACTIVE, WOUNDED, ACTIVE, ACTIVE, then casualties. All 177 protected battle/gameplay/director source hashes are unchanged.
Comparison with owner-accepted version 3: identical seed, combat duration, winner, commands, phase frames, arrival manifests, shot count, result summaries and every individual unit result state. Only siren parameters and final display sorting changed in live code. Existing capture/export validation passed, with {j['actor_frame_checks']} actor-frame checks, zero presentation/arrival/outro errors and zero HUD camera violations; no broad gameplay or performance retesting.
Video: {v['seconds']:.3f}s, 1280x720/30fps H.264/AAC, {v['bytes']} bytes, full decode passed; SHA256 {v['sha256']}. Saved as version 4 of libfile_5962de2d811081919c16f93b3f306b4c. Version 3 remains the accepted battle reference and is retained in history and siren_cards_20260914/prior_version3. Exact comparison and gain/order evidence: siren_cards_20260914/verification.json. Revised siren/card presentation awaits owner review; accepted battle behavior stays locked.
"""
p=out/'README.md';s=p.read_text(encoding='utf-8');s=s.replace('Fresh capture underway.','Capture completed successfully.').replace('New evidence will be recorded below on completion.',note.strip());p.write_text(s,encoding='utf-8')
p=r/'docs/DEAD_STREET_PROJECT_CONTROL.md';s=p.read_text(encoding='utf-8');s=s.replace('Changes implemented; recording verification underway.','Changes implemented and validated; video version 4 saved. Exact battle timing, commands, arrivals, shot count and all unit outcomes match the accepted version 3. Only the revised siren/card presentation remains for review.',1);p.write_text(s,encoding='utf-8')
p=r/'docs/DEAD_STREET_HIVE_MIND.md';s=p.read_text(encoding='utf-8');s=re.sub(r'\*\*Active objective:\*\*.*','**Active objective:** Version-3 battle OWNER-ACCEPTED. Narrow siren/result-card changes implemented and validated: 0.75 siren speed, 12 dB quieter in combat, survivors before casualties for every final result stack. Version-4 video saved; battle timing/commands/all unit outcomes exactly match version 3. Finishing scoped publication; revised presentation review next. See journal siren-cards-03.',s);s=re.sub(r'\*\*Immediate next task:\*\*.*','**Immediate next task:** Finish this narrow checkpoint/publication, then Brandon reviews the revised siren and survivor-first result stacks in version 4. Preserve the accepted battle, parked vocals and all unrelated work.',s);p.write_text(s,encoding='utf-8')
p=r/'docs/DEAD_STREET_JOURNAL.md';s=p.read_text(encoding='utf-8');s+='\n\n## 20260914-siren-cards-03 - Final refinement validated and delivered\n\n'+note+'\nScoped publication follows under existing authorization. No unrelated files staged, no new approval loop, no additional design changes.\n';p.write_text(s,encoding='utf-8')
scope=['gameplay/tactical_convoy_audio.gd','gameplay/tactical_battle_presentation.gd','tools/tactical_controls/estate_record.gd','tools/whittaker_estate/encode.py','docs/DEAD_STREET_HIVE_MIND.md','docs/DEAD_STREET_JOURNAL.md','docs/DEAD_STREET_PROJECT_CONTROL.md','docs/TACTICAL_CONTROLS_2026-09-13.md','tools/whittaker_estate/README.md','tools/whittaker_estate/record.json','tools/whittaker_estate/record_source_hashes.json','tools/whittaker_estate/delivery.json','tools/whittaker_estate/results.png','tools/whittaker_estate/siren_cards_20260914/verification.json']
(d/'scope.json').write_text(json.dumps(scope,indent=2))
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip()=='77874acc264fe3318583780bf48b0776a3eba499'
assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r,text=True).strip()
diff=subprocess.run(['git','diff','--check','--']+scope,cwd=r,capture_output=True,text=True);assert diff.returncode==0,diff.stdout
add=subprocess.run(['git','add','--']+scope,cwd=r,capture_output=True,text=True);assert add.returncode==0,add.stderr
staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r,text=True).splitlines();assert set(staged)<=set(scope)
diff=subprocess.run(['git','diff','--cached','--check'],cwd=r,capture_output=True,text=True);assert diff.returncode==0,diff.stdout
print('SCOPED_CHANGES',len(staged));print(subprocess.check_output(['git','diff','--cached','--stat'],cwd=r,text=True))
