from pathlib import Path
import subprocess,json,re,datetime
r=Path('C:/Users/brand/OneDrive/Documents/dead-street');d=r/'tools/whittaker_estate/siren_cards_20260914';scope=json.loads((d/'scope.json').read_text())
assert subprocess.check_output(['git','branch','--show-current'],cwd=r,text=True).strip()=='build/arsenal-checkpoint-20260911'
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip()=='77874acc264fe3318583780bf48b0776a3eba499'
staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r,text=True).splitlines();assert len(staged)==14 and set(staged)<=set(scope)
p=subprocess.run(['git','commit','-m','Tune TRC siren and show survivors first in results'],cwd=r,capture_output=True,text=True);print(p.stdout.splitlines()[0],flush=True);assert p.returncode==0,p.stderr
head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip();print('COMMIT',head,flush=True)
p=subprocess.run(['git','push','origin','build/arsenal-checkpoint-20260911'],cwd=r,capture_output=True,text=True,timeout=120);print(p.stdout,p.stderr,flush=True);assert p.returncode==0
remote=subprocess.check_output(['git','ls-remote','origin','refs/heads/build/arsenal-checkpoint-20260911'],cwd=r,text=True).split()[0];assert remote==head
receipt={'head':head,'remote':remote,'verified_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'pushed and verified','video_version':4,'video_sha256':'1ba06c48d84e756f09dc25ec09802423a4583f79f0ef9245c26a26384256b77f','next':'Owner reviews siren and survivor-first cards; accepted battle unchanged','unrelated_work':'preserved'};(d/'checkpoint_receipt.json').write_text(json.dumps(receipt,indent=2))
p=r/'docs/DEAD_STREET_HIVE_MIND.md';s=p.read_text(encoding='utf-8');s=s.replace('Published feedback checkpoint: 77874acc264fe3318583780bf48b0776a3eba499.','Published presentation checkpoint: '+head+'.').replace('Verified remote checkpoint: 77874acc264fe3318583780bf48b0776a3eba499.','Verified remote checkpoint: '+head+'.').replace('version-3 review next.','version-4 siren/card review next.').replace('Finishing scoped publication; revised presentation review next.','Published and verified; no active build pass. Revised presentation review next.');s=re.sub(r'\*\*Checkpoint / publication:\*\*.*','**Checkpoint / publication:** PUSHED / VERIFIED: '+head+' on origin/build/arsenal-checkpoint-20260911. Siren/card refinement and records published; video version 4 saved. Local receipt: tools/whittaker_estate/siren_cards_20260914/checkpoint_receipt.json. Post-push notes accompany the next substantive checkpoint; no receipt-only publication loop.',s);s=re.sub(r'\*\*Immediate next task:\*\*.*','**Immediate next task:** Brandon reviews the 0.75-speed, quieter-combat TRC siren and survivor-first results in video version 4. Preserve the owner-accepted version-3 battle behavior and all unrelated work; vocals remain parked.',s);p.write_text(s,encoding='utf-8')
p=r/'docs/DEAD_STREET_JOURNAL.md';s=p.read_text(encoding='utf-8');s+='\n\n## 20260914-siren-cards-04 - Narrow refinement published\n\nCommitted and pushed '+head+'; git ls-remote independently matches HEAD. Fourteen scoped files include two live presentation sources, existing capture/export telemetry, validation evidence and owning records. Video version 4 saved. Accepted battle comparison is exact across timing, commands, arrivals and every unit outcome. No active capture/build process remains. Next: owner reviews revised siren/card presentation. Unrelated work preserved. This local post-push receipt accompanies the next substantive checkpoint without another receipt-only commit.\n';p.write_text(s,encoding='utf-8')
print('PUSH_VERIFIED',head,'INDEX_EMPTY',not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r,text=True).strip(),flush=True)
