from pathlib import Path
import json,subprocess
O=Path(__file__).resolve().parent;R=O.parents[1]
receipt={'status':'complete_locally_publication_blocked_by_auto_review','origin':'https://github.com/LeadLasso-LL/DEADSTREET.git','branch':'build/arsenal-checkpoint-20260911','updated_cards':691,'trigger_models':8,'native_checks':3578,'reason':'Automatic approval review rejected executing publish.py: current 742-file artwork/evidence payload and GitHub destination require explicit trusted user approval. No staging, commit or push executed by this rejected action.'}
(O/'publication_receipt.json').write_text(json.dumps(receipt,indent=2),encoding='utf-8')
entry='\n\n## 20260915-weapon-cards-05 - Complete locally; new publication blocked\n\nAll eight trigger improvements and 691 current-weapon portraits are installed in the live sandbox and validated (3,578 native checks, 1,382 non-weapon structural comparisons, zero new side clipping). Automatic approval review rejected execution of tools/weapon_card_refresh_20260915/publish.py before it ran: the current 742-file artwork/evidence payload and GitHub destination need explicit approval in trusted user text. No staging/commit/push occurred and no workaround/retry attempted. Target https://github.com/LeadLasso-LL/DEADSTREET.git, branch build/arsenal-checkpoint-20260911. Prepared publisher verifies fresh HEAD/branch/index/protected-source/owned-file hashes and stages only owned source/art/evidence plus owned shared-record sections. Remaining step: owner explicitly approves this new batch, then execute the prepared publisher with its guards and verify remote receipt; no repeat production/testing needed unless validated files change. Reopen normal live-source Sandbox for immediate review now. Preserve concurrent Harold and menu/comparison changes.\n'
for name in ['DEAD_STREET_HIVE_MIND.md','DEAD_STREET_JOURNAL.md','DEAD_STREET_PROJECT_CONTROL.md']:
 with (R/'docs'/name).open('a',encoding='utf-8') as f:f.write(entry)
with (O/'README.md').open('a',encoding='utf-8') as f:f.write('\nPublication: complete locally; new GitHub publication blocked by automatic approval review pending explicit owner approval. See publication_receipt.json and Hive weapon-cards-05. Refresh publication-plan README hash and own record additions before executing publisher after approval; do not rerun asset production.\n')
print('RECORDED_PUBLICATION_BLOCK',flush=True)
print('STAGED_COUNT',len(subprocess.check_output(['git','diff','--cached','--name-only'],cwd=R,text=True).splitlines()),flush=True)
