from pathlib import Path
import subprocess,json
r=Path(r'C:\Users\brand\OneDrive\Documents\dead-street');d=r/'tools/whittaker_estate/resume_20260914'
def git(*args):return subprocess.check_output(['git',*args],cwd=r,text=True).strip()
assert git('rev-parse','HEAD')=='cd23759a82e0d7c2c5c1060ca9dd084cb1bab80c' and not git('diff','--cached','--name-only')
old="Local gameplay checkpoint 15c6bbc1292c745408869e545d5ae9dab31991cc is committed. Push is blocked by automatic approval review; verified remote remains 2cf7e4af5e4335683263004560127df7a08bcded on build/arsenal-checkpoint-20260911. Review declined the standing authorization recorded in the repository and requires explicit owner approval in this chat for the external GitHub payload. Do not retry or bypass that block without accepted approval."
current="PUSHED / VERIFIED, 2026-09-14: gameplay checkpoint 15c6bbc1292c745408869e545d5ae9dab31991cc and handoff checkpoint cd23759a82e0d7c2c5c1060ca9dd084cb1bab80c are published to origin/build/arsenal-checkpoint-20260911. Brandon explicitly approved the push in the active chat and will review the video shortly, then provide feedback. Owner visual/listening acceptance remains pending. This completion receipt is a local documentation-only commit; automatic approval review separately blocked its publication as outside the originally approved two-commit payload."
for rel in ['docs/DEAD_STREET_HIVE_MIND.md','docs/DEAD_STREET_PROJECT_CONTROL.md','tools/whittaker_estate/README.md']:
 p=r/rel;s=p.read_text(encoding='utf-8');assert old in s,rel;s=s.replace(old,current,1)
 if rel.endswith('DEAD_STREET_HIVE_MIND.md'):
  s=s.replace('- Latest local gameplay checkpoint:','- Published gameplay checkpoint:',1).replace('- Verified remote checkpoint: 2cf7e4af5e4335683263004560127df7a08bcded.','- Verified remote checkpoint: cd23759a82e0d7c2c5c1060ca9dd084cb1bab80c.',1).replace('- Publication blocked by automatic approval review; see current coordination below.','- Approved source/handoff push completed; this later completion receipt is local.',1)
  s=s.replace('Obtain explicit in-chat approval for the scoped estate push only because automatic approval review requires it; do not ask the owner to reconstruct the handoff. Brandon reviews','Brandon will review shortly and provide feedback on',1)
 p.write_text(s,encoding='utf-8')
entry="\n\n## 20260914-active-resume-07 - Approved push verified; completion receipt local\n\nSource: Brandon in the active build chat, 2026-09-14: \"push approved, will review video shortly and provide feedback\". This authorized the scoped estate source/art/voice/evidence/handoff push to https://github.com/LeadLasso-LL/DEADSTREET.git on build/arsenal-checkpoint-20260911. It does not imply visual or audio acceptance.\n\nFresh checks verified local cd23759, remote 2cf7e4a, exact established origin/branch, empty index, and only the two reviewed commits pending. A normal non-force push succeeded, advancing GitHub to cd23759a82e0d7c2c5c1060ca9dd084cb1bab80c; ls-remote verified equality. The earlier source push block is resolved.\n\nAutomatic approval review separately rejected creating and publishing this additional documentation commit because the current approval covered the two previously identified commits. That action was rejected before execution. This completion receipt is saved and committed locally; its publication remains pending separate approval. A first local-only attempt had a command-line quoting error before execution; writing an explicit script file resolves the serialization issue. No further publication attempt was made. Unrelated dirty work is preserved, and no gameplay edits or new tests were needed.\n\nNext: receive and acknowledge Brandon video feedback, record decisions before dependent edits, then select the next correction. Estate performance 44.42 FPS, other 17 voice banks, the pressure hook, and owner visual/listening acceptance remain open. Source and prior handoff are on GitHub; this completion note is local until its publication is approved.\n"
with (r/'docs/DEAD_STREET_JOURNAL.md').open('a',encoding='utf-8') as f:f.write(entry)
p=d/'checkpoint_receipt.json';v=json.loads(p.read_text());v.update({'remote_commit':'cd23759a82e0d7c2c5c1060ca9dd084cb1bab80c','push_status':'source_and_original_handoff_pushed_verified','approval_text':'push approved, will review video shortly and provide feedback','completion_receipt_publication':'blocked_by_automatic_review_as_additional_payload','next_step':'Owner video feedback; local completion receipt publication requires separate approval'});p.write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8')
scope=['docs/DEAD_STREET_HIVE_MIND.md','docs/DEAD_STREET_PROJECT_CONTROL.md','docs/DEAD_STREET_JOURNAL.md','tools/whittaker_estate/README.md','tools/whittaker_estate/resume_20260914/checkpoint_receipt.json']
subprocess.run(['git','add','--',*scope],cwd=r,check=True);assert set(git('diff','--cached','--name-only').splitlines())==set(scope)
subprocess.run(['git','diff','--cached','--check'],cwd=r,check=True);subprocess.run(['git','commit','-m','Record approved estate push and pending owner video feedback'],cwd=r,check=True)
print('LOCAL_RECEIPT_HEAD',git('rev-parse','HEAD'));print('INDEX',git('diff','--cached','--name-only'));print('SCOPED_DIRTY',git('status','--short','--untracked-files=no','--',*scope));print('NO_ADDITIONAL_PUSH_ATTEMPTED')
