from pathlib import Path
import json
r=Path(r'C:\Users\brand\OneDrive\Documents\dead-street')
event="## 20260915-doble-ocho-01 - Fourth tactical map and scripted video authorized\nStatus: IN PROGRESS; source Brandon's current chat6a4bd31e258d. Owner delegates creative setting/factions/layout for a surprise overnight fourth map, targeted6v6/7v7 between Harold and bridge, and requests a complete scripted battle video. No approval question needed for these authored choices.\nFresh repo: build/arsenal-checkpoint-20260911 HEAD408f62cb2c3642e4ba9e33713f531c35757a6a2f; index empty. Mixed Harold/range/outcome/character/opening work preserved. tools/fourth_map_20260915/initial_status.txt and source_export.json preserve read baseline.\nSelected new authored scenario: Doble Ocho Auto Yard, south-side New Briarport. Calle Ocho holds a working repair/salvage business; Sierra Roja launches a seven-person seizure raid. Rivalry/south-side overlap grounded in owner faction reference05; specific business and encounter are assistant-authored for this delegated first pass, not preexisting campaign canon. Target96x64 world, two gates, central scrap-car cover, sheltered northern route and southern service flank. Seven-person show uses actual seats and canonical vehicles, auto-deployed real cover before combat, native deterministic orders without health/winner overrides.\nPreserve shared1.6 fleet scale,1.48 actors/8x6 projection, fixed bridge-width HUD, selected individual/class range rules, survivor-first results, parked vocals, owner-assigned faction tracks and quiet combat mix. Carry Harold1.35 cover standoff/2.4 offered-slot spacing to new layout only. Develop surroundings beyond intro viewport. Use physical collision/cover matching authored art, solid building corners, open visible gates. No broad combat/AI/balance changes.\nScope: new catalog/art/setup/scenario/fixtures; narrow shared map registration and presentation hooks. Existing three maps remain behaviorally protected. Next: implement map and sandbox choice, native geometry/route/arrival/visual checks, rehearse7v7 and capture complete phone-friendly battle video. Visual acceptance remains OWNER REVIEW after delivery; no publication performed.\n"
for name in ['docs/DEAD_STREET_HIVE_MIND.md','docs/DEAD_STREET_JOURNAL.md']:
 p=r/name;s=p.read_text(encoding='utf-8');assert '20260915-doble-ocho-01' not in s
 if 'HIVE' in name:
  old=next(x for x in s.splitlines() if x.startswith('**Active objective (2026-09-15):**'));s=s.replace(old,'**Active objective (2026-09-15):** BUILD is creating Doble Ocho Auto Yard, a new6v6/7v7 south-side map and scripted battle video under owner-delegated creative scope. See doble-ocho-01 and tools/fourth_map_20260915/. Harold cover pass complete, appearance still review pending.')
 p.write_text(s+'\n\n'+event,encoding='utf-8')
(r/'tools/fourth_map_20260915/BRIEF.md').write_text(event,encoding='utf-8')
print('Fourth-map scope and baseline recorded')
