from pathlib import Path
import subprocess,json,hashlib,re,sys
r=Path(r'C:\Users\brand\OneDrive\Documents\dead-street');out=r/'tools/whittaker_estate';o=out/'width_scenery_20260914';v=json.loads((out/'transfer.json').read_text());c=json.loads((o/'verification.json').read_text());j=json.loads((out/'record.json').read_text())
assert sys.argv[1:]==['--saved-version','6','--sha',v['sha256']]
assert all(c['accepted_battle_comparison'].values()) and not c['changed_protected_sources'] and v['decoded_to_end']
note="IMPLEMENTED / VALIDATED; owner presentation review pending. The estate driveway border meets the public road at x139 with no pavement lip. Shared combat HUD fills the viewport width with 12 logical-unit edge insets while retaining the accepted 226-unit height and uniform text scale; 16 units use two 46-unit card rows. The intro surroundings now continue through fields, wooded belts, access lane, neighboring lots/buildings and utility poles. The bake covers (-1200,-900) through (2896,1404); camera zoom/pan code and fightable geometry are unchanged. "+f"Native HUD: 834 checks across bridge/estate and three screen sizes, zero errors. Final capture: {j['actor_frame_checks']} actor-frame checks, zero presentation, arrival, outro or HUD camera violations. Battle comparison against version 4 is exact across seed, timing, phase frames, commands, passenger manifests, shot count, results and every unit outcome; version 4 had already matched owner-accepted version 3. All {c['protected_sources']} protected source hashes match. Siren, survivor-first results, units, arrivals and combat remain unchanged.\nVideo version 6: {v['seconds']:.3f}s, 1280x720/30fps H.264/AAC, {v['bytes']} bytes, decoded through the end. SHA256 {v['sha256']}. Saved under existing libfile_5962de2d811081919c16f93b3f306b4c; version 4 is preserved in width_scenery_20260914/prior_version4. Evidence: width_scenery_20260914/verification.json and hud_layout.json, intro_full.png, opening_cover.png and record.json. Reproduce with run.py pack, --check=estate_bake, repack, --check=hud_layout_review / estate_scenery_preview, then record_worker.py and encode.py. Never repack during capture. No broad gameplay suite or fresh performance benchmark; historical estate performance and global caps remain open.\n"
for rel,title in [('tools/whittaker_estate/README.md','## Driveway, shared HUD width and intro surroundings - 2026-09-14'),('docs/DEAD_STREET_PROJECT_CONTROL.md','# Current milestone - estate presentation refinement - 2026-09-14')]:
 p=r/rel;s=p.read_text(encoding='utf-8');p.write_text(title+'\n\n'+note+'\n'+s,encoding='utf-8')
p=r/'docs/TACTICAL_CONTROLS_2026-09-13.md';s=p.read_text(encoding='utf-8');s=s.replace('226 logical units in the 1152x800 reference frame, scaled to fit both viewport dimensions.','226 logical units in the 1152x800 reference frame, with height/text scale bounded by both viewport dimensions. The surface fills viewport width; its visible panel has 12 logical-unit insets on each side. Width is independent of the height-limited scale, and is identical across maps at matching viewports. This latest owner width correction supersedes the fixed 1152-unit surface width.');p.write_text(s,encoding='utf-8')
p=r/'docs/MAP_BUILDING_STANDARD.md';s=p.read_text(encoding='utf-8');s+='\n\n## Estate intro surroundings correction - 2026-09-14\n\nBrandon requested continuous developed context beyond the fightable estate visible at the existing intro zoom. Expand and furnish the static scenery coverage rather than changing the approved camera. Estate now has a 4096x2304 bake at origin (-1200,-900), continuing public road, fields, tree belts, utility lines and neighboring lots. These remain noncombat scenery; no collision, cover or route changes. The main driveway and its border end flush at the public road edge. Native intro and road-junction inspection passed; owner visual review remains pending. Detailed evidence and reproduction: tools/whittaker_estate/README.md.\n';p.write_text(s,encoding='utf-8')
p=r/'docs/DEAD_STREET_HIVE_MIND.md';s=p.read_text(encoding='utf-8');s=re.sub(r'\*\*Active objective:\*\*.*','**Active objective:** Owner driveway seam, full-width shared HUD and estate intro-surroundings refinements are implemented and validated; version-6 video saved. Original zoom and accepted battle are unchanged. Finishing scoped publication; then owner presentation review. See journal width-scenery-03.',s);s=re.sub(r'\*\*Immediate next task:\*\*.*','**Immediate next task:** Publish this validated presentation checkpoint, then Brandon reviews video version 6. Preserve accepted battle behavior, current siren/result ordering, parked vocals and unrelated work.',s)
s=re.sub(r'\*\*Latest estate evidence:\*\*.*','**Latest estate evidence:** 834 native HUD checks across bridge/estate and three viewports; '+str(j['actor_frame_checks'])+' actor-frame checks in final capture, zero presentation/route/HUD camera errors. Version-5 video 88.197s; native combat 48.30s with four Whittaker survivors. Exact accepted-battle comparison and 195 protected source hashes pass; see estate README.',s)
s=s.replace('Version 3 delivered; source 77874ac published; owner review pending. Retains estate scope.','Version-3 battle owner-accepted; version-6 presentation refinement validated and saved, scoped publication underway. Retains estate scope.');p.write_text(s,encoding='utf-8')
with (r/'docs/DEAD_STREET_JOURNAL.md').open('a',encoding='utf-8') as f:f.write('\n\n## 20260914-width-scenery-03 - Revised presentation validated and delivered\n\n'+note+'\nScoped publication follows under standing authorization; unrelated work and the separate UI walkthrough are preserved.\n')
scope=['gameplay/tactical_command_hud.gd','gameplay/whittaker_estate_art.gd','assets/art/whittaker_estate/ground.png','tools/tactical_controls/estate_bake.gd','tools/tactical_controls/hud_layout_review.gd','tools/tactical_controls/estate_scenery_preview.gd','docs/DEAD_STREET_HIVE_MIND.md','docs/DEAD_STREET_JOURNAL.md','docs/DEAD_STREET_PROJECT_CONTROL.md','docs/TACTICAL_CONTROLS_2026-09-13.md','docs/MAP_BUILDING_STANDARD.md','tools/whittaker_estate/README.md','tools/whittaker_estate/record.json','tools/whittaker_estate/record_source_hashes.json','tools/whittaker_estate/delivery.json','tools/whittaker_estate/intro_full.png','tools/whittaker_estate/opening_cover.png']+['tools/whittaker_estate/width_scenery_20260914/'+p for p in ['verification.json','hud_layout.json','river_bridge_1920x1080.png','whittaker_estate_1920x1080.png','verify.py']]
(o/'scope.json').write_text(json.dumps(scope,indent=2),encoding='utf-8')
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip()=='555d6925fbf1a965a3b8027bc2f5186fdd19d4bc'
assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r,text=True).strip()
q=subprocess.run(['git','diff','--check','--']+scope,cwd=r,capture_output=True,text=True);assert q.returncode==0,q.stdout
subprocess.run(['git','add','--']+scope,cwd=r,check=True)
staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r,text=True).splitlines();assert set(staged)<=set(scope)
subprocess.run(['git','diff','--cached','--check'],cwd=r,check=True)
print('SCOPED_FILES',len(staged),flush=True);print(subprocess.check_output(['git','diff','--cached','--stat'],cwd=r,text=True),flush=True)