from pathlib import Path
import subprocess,json,re,datetime
r=Path(r'C:\Users\brand\OneDrive\Documents\dead-street');o=r/'tools/whittaker_estate/width_scenery_20260914';scope=json.loads((o/'scope.json').read_text());v=json.loads((r/'tools/whittaker_estate/transfer.json').read_text())
assert subprocess.check_output(['git','branch','--show-current'],cwd=r,text=True).strip()=='build/arsenal-checkpoint-20260911'
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip()=='555d6925fbf1a965a3b8027bc2f5186fdd19d4bc'
staged=subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r,text=True).splitlines();assert len(staged)==21 and set(staged)<=set(scope)
subprocess.run(['git','diff','--cached','--check'],cwd=r,check=True)
p=subprocess.run(['git','commit','-m','Unify HUD width and finish estate surroundings'],cwd=r,capture_output=True,text=True);assert p.returncode==0,p.stderr;print(p.stdout.splitlines()[0],flush=True)
head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip();print('COMMIT',head,flush=True)
p=subprocess.run(['git','push','origin','build/arsenal-checkpoint-20260911'],cwd=r,capture_output=True,text=True,timeout=120);print(p.stdout,p.stderr,flush=True);assert p.returncode==0
remote=subprocess.check_output(['git','ls-remote','origin','refs/heads/build/arsenal-checkpoint-20260911'],cwd=r,text=True).split()[0];assert remote==head
receipt={'head':head,'remote':remote,'status':'pushed and verified','verified_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'video_version':6,'video_sha256':v['sha256'],'next':'Owner reviews driveway seam, shared HUD width and developed intro surroundings; accepted battle/camera/audio unchanged','unrelated_work':'preserved'};(o/'checkpoint_receipt.json').write_text(json.dumps(receipt,indent=2),encoding='utf-8')
p=r/'docs/DEAD_STREET_HIVE_MIND.md';s=p.read_text(encoding='utf-8');s=s.replace('Published presentation checkpoint: 555d6925fbf1a965a3b8027bc2f5186fdd19d4bc.','Published presentation checkpoint: '+head+'.').replace('Verified remote checkpoint: 555d6925fbf1a965a3b8027bc2f5186fdd19d4bc.','Verified remote checkpoint: '+head+'.').replace('version-4 siren/card review next.','version-6 presentation review next.').replace('Finishing scoped publication; then owner presentation review.','Published and verified; owner presentation review next.').replace('scoped publication underway. Retains estate scope.','source published and verified. Retains estate scope.')
s=re.sub(r'\*\*Checkpoint / publication:\*\*.*','**Checkpoint / publication:** PUSHED / VERIFIED: '+head+' on origin/build/arsenal-checkpoint-20260911. Revised HUD/scenery video saved as version 6; version 5 was a superseded duplicate of version 4. Receipt: tools/whittaker_estate/width_scenery_20260914/checkpoint_receipt.json. Post-push notes accompany the next substantive checkpoint.',s)
s=re.sub(r'\*\*Immediate next task:\*\*.*','**Immediate next task:** Brandon reviews video version 6 for the flush driveway, full-width compact HUD and developed intro surroundings. Preserve accepted battle, original camera zoom, current siren/result ordering, parked vocals and unrelated work. No active estate build/capture remains.',s);p.write_text(s,encoding='utf-8')
with (r/'docs/DEAD_STREET_JOURNAL.md').open('a',encoding='utf-8') as f:f.write('\n\n## 20260914-width-scenery-04 - Presentation checkpoint published\n\nCommitted and pushed '+head+'; independent git ls-remote matches HEAD. Twenty-one scoped files include two live presentation sources, baked ground, focused native fixtures/evidence and owning records. Video version 6 is saved and transfer verified. Final record.json is byte-for-byte unchanged from the previous accepted-battle replay, so Git has no new record diff. Unrelated work and parallel UI capture scope preserved; no active estate build/capture remains. Next: owner presentation review. Local post-push hive/journal/receipt accompany the next substantive checkpoint, without a receipt-only commit loop.\n')
print('PUSH_VERIFIED',head,'INDEX_EMPTY',not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=r,text=True).strip(),flush=True)
print(subprocess.check_output(['git','status','--short','--untracked-files=no'],cwd=r,text=True),flush=True)