from pathlib import Path
import re,json,subprocess,sys
sys.stdout.reconfigure(encoding='utf-8')
root=Path(r'C:\Users\brand\OneDrive\Documents\dead-street')
for rel,addition in {"docs/DEAD_STREET_JOURNAL.md":"\n\n## 20260914-faction-audio-preview-03 - Full audition set saved for owner listening\n\nIMPLEMENTED / TECHNICALLY VALIDATED / SAVED, OWNER APPROVAL PENDING. All 18 original instrumental sketches (21-32s each) delivered through a 473.106333s labeled H.264/AAC reel with 18 chapters, self-contained HTML audio player and 18 standalone 192kbps stereo MP3s. All 20 files saved successfully; exact identities/versions in tools/faction_audio_preview_20260914/delivery_receipt.json. Reel libfile_eb40eada2dd48191a5a98fcdd40509a2 v0; player libfile_4e69138b869481918a163a16e0d153c0 v0. Reel SHA256 a6f19aaab37d35cd2c8b683ba51b22a758e49dc7c87eea85af8961b7081fc3af.\n\nPASS: full FFmpeg decode of all 18 MP3s and complete reel; all 18 chapters and total duration verified; integrated loudness -18.27 to -18.24 LUFS, highest encoded true peak -2.23 dBTP; finite/nonzero PCM; all 18 title cards visually inspected. No independent auditory or HTML-browser interaction validation claimed. No in-game tests: no runtime source/audio changes or integration. Samples use original scores with sampled instruments and synthesis, not live-band recordings. Saffar plucked-string timbres approximate the proposed oud/qanun direction; artistic/genre fidelity is for listening review.\n\nReproducible composer, packaging script, exact scored manifest, instrument-bank license/hash, review index, validation and delivery/source receipts saved in the remote repository's isolated tools/faction_audio_preview_20260914 scope. Audio previews are durably saved separately, not installed as assets. Existing five identities, parked vocals and concurrent title/tutorial work preserved. Next: Brandon hears all 18 and names keeps/changes/rejections. Revise named previews before any game binding or loop-master work. Source-only checkpoint publication follows; shared mixed documentation remains safely preserved in the working tree.\n","docs/DEAD_STREET_PROJECT_CONTROL.md":"\n\n## 2026-09-14 — All-faction audio audition 01\n\nPREVIEW PRODUCED / TECHNICALLY VALIDATED / SAVED; OWNER LISTENING APPROVAL PENDING. Eighteen previously unscored faction identities now have 21-32-second original instrumental sketches. Labeled 7m53s reel, self-contained player and individual MP3s saved; full decode/level gates passed, all 18 title cards visually checked. No runtime integration, loop-master preparation or independent auditory-quality approval. Existing five themed sources unchanged by this pass; vocals remain parked. [Production and review handoff](../tools/faction_audio_preview_20260914/README.md), [directions](FACTION_AUDIO_DIRECTION_2026-09-14.md), journal faction-audio-preview-03. Next: owner hears all samples, then targeted revisions.\n"}.items():
    p=root/rel
    with p.open('a',encoding='utf-8') as f: f.write(addition)
p=root/'docs/FACTION_AUDIO_DIRECTION_2026-09-14.md'; s=p.read_text(encoding='utf-8')
s=s.replace('Status: PROPOSED for owner review, not approved sound design or produced assets.','Status: AUDITION 01 PRODUCED AND SAVED; owner listening approval pending. All 18 directions have private samples; no runtime integration.')
s=s.replace('Brandon requests music/audio for every playable faction and, for this turn, a list of vibes for factions without their own audio. Existing faction vocal/gibberish work stays parked. No new audio is generated or installed in this pass.','Initial request was the direction list below. Brandon subsequently authorized all 18 previews: “Go for it. I wanna hear them all before approving.” Eighteen original sampled-instrument/synthesis sketches are now produced and saved. Existing faction vocals/gibberish remain parked. No new runtime audio is installed.')
s += '\n\n## Audition 01 handoff\n\nAll 18 directions now have labeled listening previews, pending owner approval. See ../tools/faction_audio_preview_20260914/README.md, review_index.json, validation.json and delivery_receipt.json for exact files, checks and limits. Historical next-step text above is superseded: owner listening review is now next. No independent artistic/listening approval or in-game loop/transition validation claimed.\n'
p.write_text(s,encoding='utf-8')
p=root/'docs/DEAD_STREET_HIVE_MIND.md'; s=p.read_text(encoding='utf-8')
s=re.sub(r'\*\*Active objective:\*\* Owner authorized listening previews[^\n]*','**Active objective:** All 18 remaining faction audio audition sketches are produced, technically validated and saved for owner listening approval. See tools/faction_audio_preview_20260914/README.md and journal faction-audio-preview-03. No game audio integration; existing five identities and parked vocals preserved.',s)
s=re.sub(r'\*\*Immediate next task:\*\* Produce all 18 private instrumental sketches[^\n]*','**Immediate next task:** Brandon hears the labeled all-18 audition reel or individual previews, then names keeps/changes/rejections. Revise only the named sketches. Game integration, loop masters and map-wide bindings remain pending explicit sound approval. Preserve concurrent tutorial/title scopes.',s)
p.write_text(s,encoding='utf-8')
assert 'faction-audio-preview-03' in (root/'docs/DEAD_STREET_JOURNAL.md').read_text(encoding='utf-8')
assert 'AUDITION 01 PRODUCED' in (root/'docs/FACTION_AUDIO_DIRECTION_2026-09-14.md').read_text(encoding='utf-8')
print('Saved and verified final audio records; owner listening review next.')
