from pathlib import Path
import re,json,subprocess,hashlib
r=Path(r'C:\Users\brand\OneDrive\Documents\dead-street')
entry="\n\n## 20260914-faction-audio-rhythm-01 — owner rejects rhythm; Bìtiān direction rejected\n\nOwner feedback: “im trying to just accept it and say ok but like why is everything off beat like crazy...are you able to understand what on beat music sounds like?” Follow-up: “also bitian nocturnal trip hop is just not it at all”. Individual04 is not accepted; do not interpret the owner's earlier praise for contrast03 direction as approval of the full set. Bìtiān's nocturnal trip-hop concept is rejected, not merely its timing. No replacement Bìtiān genre has been approved.\n\nSource diagnosis: authored beat locations vary inconsistently across instruments. Calle Ocho's nominal backbeats are displaced by 0.08–0.16 beats (roughly 68–136 ms at 70.4 BPM), while kick/bass/guitar use unrelated fractional placements. Several other scores deliberately use irregular offsets and unusual meters. Unusual meters and syncopation are not inherently wrong; the implementation lacked a reliable common rhythmic foundation. These authored placements, not the renderer's small +/-3 ms humanization, are the primary identified timing defect. Cannot establish every perceived issue from score alone.\n\nAssistant acknowledged overcorrecting sameness with rhythmic irregularity and failing to establish groove. Prior decode/loudness/hash checks proved file integrity, not musical quality. No independent listening validation occurred; be candid about inability to reliably audition rendered music by ear in this workflow. Owner should not need to accept a result they dislike.\n\nNext: rebuild the rhythmic foundation around a clear repeatable pulse, coherent kick/bass/backbeat relationships and deliberate subdivisions; validate a small concrete groove before another full-faction render. Distinction should come from composition, instruments, sound and arrangement, not arbitrary timing. Bìtiān needs a new musical concept informed by further owner direction/reference, not polishing the rejected trip-hop track. Preserve all earlier media as failed/reference evidence. No new render, runtime edits or Git publication in this diagnostic block.\n\nFresh remote HEAD ca7688947ef3ae67bdb136359c43666fe4d99e70. Audio source folder and topic remain untracked. Another work scope has staged shared records and music-controls files; preserve that index exactly and append/merge our working documentation only. No staging/unstaging/commit/push performed.\n"
before=subprocess.check_output(['git','diff','--cached','--binary'],cwd=r)
for n in ['docs/DEAD_STREET_JOURNAL.md','docs/DEAD_STREET_PROJECT_CONTROL.md']:
    with (r/n).open('a',encoding='utf-8') as f:f.write(entry)
p=r/'docs/FACTION_AUDIO_DIRECTION_2026-09-14.md';s=p.read_text(encoding='utf-8')
s=re.sub(r'^Status:.*','Status: INDIVIDUAL04 FAILED OWNER RHYTHM REVIEW. BITIAN NOCTURNAL TRIP-HOP DIRECTION REJECTED. No new audio accepted for installation.',s,count=1,flags=re.M)
p.write_text(s+entry,encoding='utf-8')
p=r/'docs/DEAD_STREET_HIVE_MIND.md';s=p.read_text(encoding='utf-8')
s=re.sub(r'\*\*Active objective:\*\*[^\n]*','**Active objective:** Owner rejects individual04 rhythm as off-beat and specifically rejects Bitian nocturnal trip-hop. Source diagnosis identifies inconsistent authored timing. Read journal faction-audio-rhythm-01 and current faction audio topic. No new music accepted or installed.',s,count=1)
s=re.sub(r'\*\*Immediate next task:\*\*[^\n]*','**Immediate next task:** Establish a clear, coherent groove in a small rhythm correction before any further full-set render. Bitian requires a new concept; no replacement direction approved. Do not infer artistic success from file or score checks. Preserve prior previews, five existing identities, parked vocals and concurrent work.',s,count=1)
p.write_text(s,encoding='utf-8')
after=subprocess.check_output(['git','diff','--cached','--binary'],cwd=r);assert before==after
assert all('20260914-faction-audio-rhythm-01' in (r/n).read_text(encoding='utf-8') for n in ['docs/DEAD_STREET_JOURNAL.md','docs/DEAD_STREET_PROJECT_CONTROL.md','docs/FACTION_AUDIO_DIRECTION_2026-09-14.md'])
print(json.dumps({'feedback_recorded':True,'existing_index_preserved':True,'new_audio_rendered':False,'runtime_changed':False}))
