from pathlib import Path
import re,subprocess,json
r=Path(r'C:\Users\brand\OneDrive\Documents\dead-street')
entry="\n\n## 20260914-faction-audio-shared-music-01 — owner chooses imported soundtrack for dual use\n\nOwner: “i think i have a better idea. all the soundcloud beats i import and make menu music will be used for the faction audio. great dual use”. ACCEPTED PRODUCT DIRECTION: owner-imported SoundCloud/menu tracks will also supply faction music. Stop the separately generated faction-composition pass. This supersedes rhythm-01's next step to make another programmed groove and the pending individual04 approval plan. Preserve prior previews and failure records as historical evidence; no new generated faction tracks or vocals.\n\nVerified current source: gameplay/sandbox_menu_music.gd currently loads a single asset, res://assets/menu/opening/B-22_Dead_Street.mp3. There is no implemented shared catalogue or faction-track mapping in that script. Native menu music pauses when sandbox UI is hidden. Current hive music-import-readiness-01 assigns incoming SoundCloud URL intake / queue implementation to chat3ca0ac6a33c3; preserve its scope and opening/portrait ownership. Fresh repository HEAD ec7a60edaaa7d25493bdae523a6ab44d42148391; index empty before this documentation block.\n\nImplementation direction: import a track once with source title/artist provenance, use its shared asset identity in the menu playlist and faction music associations. Keep faction assignments separate from menu shuffle state. Existing spatial vehicle/property playback and restrained combat mix remain applicable. This is a proposed implementation structure for the owner's approved dual-use concept, not a claim it has been built. Preserve accepted nonmusic engines/sirens/weapons and the parked-vocals rule. No immediate replacement of existing installed faction sounds or arbitrary assignment of the sole signature track.\n\nExact remaining gaps: additional imported tracks, owner-selected/accepted faction associations, shared catalogue and battle integration. No new URLs or specific faction associations supplied in this message. Next: continue established import workflow, then assign suitable imported tracks to factions and implement/validate shared-asset playback and combat ducking. This does not require resuming generated Bìtiān music. Discussion/coordination only: no runtime/media edit, import, commit or push; documentation saved and verified.\n"
before=subprocess.check_output(['git','diff','--cached','--binary'],cwd=r)
for n in ['docs/DEAD_STREET_JOURNAL.md','docs/DEAD_STREET_PROJECT_CONTROL.md']:
    with (r/n).open('a',encoding='utf-8') as f:f.write(entry)
p=r/'docs/FACTION_AUDIO_DIRECTION_2026-09-14.md';s=p.read_text(encoding='utf-8')
s=re.sub(r'^Status:.*','Status: OWNER-IMPORTED SOUNDCLOUD/MENU TRACKS WILL ALSO SUPPLY FACTION MUSIC. GENERATED COMPOSITION PASS STOPPED. Shared catalogue and faction assignments pending.',s,count=1,flags=re.M);p.write_text(s+entry,encoding='utf-8')
p=r/'docs/DEAD_STREET_HIVE_MIND.md';s=p.read_text(encoding='utf-8')
s=re.sub(r'\*\*Active objective:\*\*[^\n]*','**Active objective:** Owner-selected SoundCloud imports will serve both menu playlist and faction music. Generated faction composition pass is stopped. See journal faction-audio-shared-music-01 and current faction audio topic. Existing native menu has one signature track; shared catalogue/faction assignments remain unimplemented.',s,count=1)
s=re.sub(r'\*\*Immediate next task:\*\*[^\n]*','**Immediate next task:** Continue established SoundCloud intake with chat3ca0ac6a33c3, then associate imported tracks with factions and implement shared-asset battle playback with restrained spatial/combat mix. Actual track-to-faction assignments remain open. Preserve opening/menu/portrait work and accepted nonmusic sounds; vocals stay parked.',s,count=1)
s+='\n\n## Shared menu / faction soundtrack decision - 20260914-faction-audio-shared-music-01\nOwner chose all imported SoundCloud/menu beats as the source pool for faction music too. Stop generated faction composition work. Import once and reference shared track identity in menu/faction assignments; associations and runtime shared catalogue are next work, not implemented. Coordinate with existing music-import readiness scope; preserve title/signature continuity and accepted nonmusic sounds. See current faction audio topic and journal for exact gaps.\n'
p.write_text(s,encoding='utf-8')
assert subprocess.check_output(['git','diff','--cached','--binary'],cwd=r)==before
assert all('20260914-faction-audio-shared-music-01' in (r/n).read_text(encoding='utf-8') for n in ['docs/DEAD_STREET_HIVE_MIND.md','docs/DEAD_STREET_JOURNAL.md','docs/DEAD_STREET_PROJECT_CONTROL.md','docs/FACTION_AUDIO_DIRECTION_2026-09-14.md'])
print(json.dumps({'shared_soundtrack_decision_saved':True,'generated_pass_stopped':True,'index_preserved':True,'runtime_changed':False}))
