from pathlib import Path
R=Path(__file__).resolve().parent/'pistol_portrait_20260914'
files={"install.py":"\"\"\"Install only reviewed, hash-verified portrait files; safe to repeat.\"\"\"\nfrom pathlib import Path\nimport hashlib,json,shutil\nR=Path(__file__).resolve().parents[2];O=Path(__file__).parent\ndef sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()\nreport=json.loads((O/'validation.json').read_text())\nprotected=json.loads((O/'protected_hashes.json').read_text())\nassert all(sha(R/p)==h for p,h in protected.items()),'Protected source changed; reconcile before installation'\nfor item in report['items']:\n candidate=O/'candidates'/(item['variant']+'.png');target=R/item['portrait']\n assert sha(candidate)==item['candidate_sha256'],item['variant']\n assert sha(target) in [item['before_sha256'],item['candidate_sha256']],item['variant']\nfor item in report['items']:shutil.copyfile(O/'candidates'/(item['variant']+'.png'),R/item['portrait'])\nassert all(sha(R/p)==h for p,h in protected.items())\nprint('INSTALLED',len(report['items']),'PROTECTED',len(protected),flush=True)\n","native_card_checks.gd":"extends SceneTree\nconst Anim=preload(\"res://battle/presentation/tactical_unit_animation_catalog.gd\")\nfunc _initialize():\n var rows=JSON.parse_string(FileAccess.get_file_as_string(\"res://tools/pistol_portrait_20260914/inventory.json\"))\n var checks=0\n var failures=[]\n for row in rows:\n  var specialist=\"mercer_dual_glock\" if row.group==\"mercer\" else \"\"\n  var faction=\"mercer\" if row.group==\"mercer\" else str(row.faction)\n  var model=\"glock_17\" if row.group==\"mercer\" else str(row.model)\n  var variant=Anim.variant_for(faction,\"pistol\",model,specialist)\n  if variant!=row.variant:failures.append(str(row.variant)+\": binding\");continue\n  checks+=1\n  var path=Anim.atlas_path(variant,\"portraits\")\n  if path!=\"res://\"+str(row.portrait):failures.append(variant+\": path\");continue\n  checks+=1\n  var texture=Anim._load_texture(path)\n  if texture==null:failures.append(variant+\": missing texture\");continue\n  checks+=1\n  var actual=texture.get_image()\n  var expected=Image.load_from_file(path)\n  actual.convert(Image.FORMAT_RGBA8)\n  expected.convert(Image.FORMAT_RGBA8)\n  if actual.get_size()!=expected.get_size() or actual.get_data()!=expected.get_data():failures.append(variant+\": stale imported image\");continue\n  checks+=1\n var result={\"portraits\":rows.size(),\"checks\":checks,\"failures\":failures}\n FileAccess.open(\"res://tools/pistol_portrait_20260914/native_card_checks.json\",FileAccess.WRITE).store_string(JSON.stringify(result,\"  \"))\n print(\"PISTOL_CARD_CHECKS \",JSON.stringify(result))\n quit(0 if failures.is_empty() else 1)\n"}
for name,source in files.items():(R/name).write_text(source,encoding='utf-8')
import subprocess,sys
subprocess.run([sys.executable,str(R/'install.py')],check=True)
p=subprocess.run([r'C:\Users\brand\OneDrive\Documents\Godot\Godot_v4.7.2-stable_win64_console.exe','--headless','--path',str(R.parents[1]),'--script',str(R/'native_card_checks.gd')],capture_output=True,text=True)
(R/'native_card_checks.log').write_text(p.stdout+p.stderr,encoding='utf-8')
print(p.stdout+p.stderr)
raise SystemExit(p.returncode)
