from pathlib import Path
import subprocess
r=Path(__file__).resolve().parent.parent
o=r/'tools/pistol_portrait_20260914'
(o/'native_card_checks.gd').write_text("extends SceneTree\nconst Anim=preload(\"res://battle/presentation/tactical_unit_animation_catalog.gd\")\nfunc _initialize():\n var rows=JSON.parse_string(FileAccess.get_file_as_string(\"res://tools/pistol_portrait_20260914/inventory.json\"))\n var checks=0\n var failures=[]\n for row in rows:\n  var specialist=\"mercer_dual_glock\" if row.group==\"mercer\" else \"\"\n  var faction=\"mercer\" if row.group==\"mercer\" else str(row.faction)\n  var model=\"glock_17\" if row.group==\"mercer\" else str(row.model)\n  var variant=Anim.variant_for(faction,\"pistol\",model,specialist)\n  if variant!=row.variant:failures.append(str(row.variant)+\": binding\");continue\n  checks+=1\n  var path=Anim.atlas_path(variant,\"portraits\")\n  if path!=\"res://\"+str(row.portrait):failures.append(variant+\": path\");continue\n  checks+=1\n  var texture=Anim._load_texture(path)\n  if texture==null:failures.append(variant+\": missing texture\");continue\n  checks+=1\n  var actual=texture.get_image()\n  var expected=Image.new()\n  expected.load_png_from_buffer(FileAccess.get_file_as_bytes(path))\n  actual.convert(Image.FORMAT_RGBA8)\n  expected.convert(Image.FORMAT_RGBA8)\n  var mismatch=0\n  for y in expected.get_height():\n   for x in expected.get_width():\n    var a=actual.get_pixel(x,y)\n    var b=expected.get_pixel(x,y)\n    if a.a!=b.a or (b.a>0 and a!=b):mismatch+=1\n  if mismatch>0:failures.append(variant+\": \"+str(mismatch)+\" visible pixel mismatches\");continue\n  checks+=1\n var result={\"portraits\":rows.size(),\"checks\":checks,\"failures\":failures}\n FileAccess.open(\"res://tools/pistol_portrait_20260914/native_card_checks.json\",FileAccess.WRITE).store_string(JSON.stringify(result,\"  \"))\n print(\"PISTOL_CARD_CHECKS \",JSON.stringify(result))\n quit(0 if failures.is_empty() else 1)\n",encoding='utf-8')
p=subprocess.run([r'C:\Users\brand\OneDrive\Documents\Godot\Godot_v4.7.2-stable_win64_console.exe','--headless','--path',str(r),'--script',str(o/'native_card_checks.gd')],capture_output=True,text=True)
(o/'native_card_checks.log').write_text(p.stdout+p.stderr,encoding='utf-8')
print(p.stdout+p.stderr)
raise SystemExit(p.returncode)
