from pathlib import Path
import json
out=Path(__file__).resolve().parent;root=out.parents[1]
v=json.loads((out/'native_validation.json').read_text());c=json.loads((out/'correction_validation.json').read_text());assert len(v['checks'])==115 and not v['failures'] and all(c.values())
a=json.loads((out/'approved_assignments.json').read_text(encoding='utf-8'));assert a['status']=='owner_approved'
text='# Approved faction music assignments\n\nFinal: 21 factions / 21 unique loops. Owner corrected Calle Ocho to Glock — B-22; La Unión del Sur retains Burn — B-22. All other screenshot choices are retained. TRC and NBPD keep their existing sirens.\n\n| Faction | Track | Artist |\n| --- | --- | --- |\n'
for row in a['assignments']:text+='| '+row['faction']+' | '+row['track']+' | '+row['artist']+' |\n'
text+='\nSpatial audio uses each side’s assigned loop: the Harold/estate defender building entrance, otherwise convoy transport, with a fixed-position fallback when no vehicle exists. Existing combat ducking and winning-loop continuity remain; old Harold beat is suppressed when faction music is present. Menu tracks and all audio files are unchanged.\n\nValidation: 115 native wiring checks across Harold/bridge/estate, both sides, exact streams, 30-second wraps, winner continuity, loser background and exit stop. Both authority implementations compared against the previous source for stream data, loop limits, gain, pitch, range, attenuation, panning and metadata. Then 13 focused checks passed for the final Calle Ocho correction: 21 unique assignments, both side streams/anchors/wraps, unchanged Union Burn and authority exclusions. Historical native_validation.json covers pre-correction wiring; correction_validation.json covers the changed mapping. The first wiring declaration issue was fixed; harness result/listener warm-up issues were corrected. No subjective listening or mix-approval claim.\n\nFinal mapping: approved_assignments.json. Native sources: check_native.gd and check_correction.gd. Before-source for siren equivalence: before_tactical_convoy_audio.gd. Runtime patch and protected final hashes are retained. Picker saved choices also corrected. Publication receipt identifies actual Git status; do not infer publication from local completion.\n'
(out/'README.md').write_text(text,encoding='utf-8',newline='\n')
p=json.loads((out/'publication_payload.json').read_text(encoding='utf-8'))
(out/'publish.py').write_text(p['pub'],encoding='utf-8',newline='\n')
entry='\n\n## 20260915-faction-music-apply-03 - Calle Ocho corrected; all assignments final and validated\n\nOwner explicitly directed Glock for Calle Ocho. Final mapping has21 distinct tracks for21 non-authority factions; La Union del Sur keeps Burn and the other20 screenshot choices are unchanged. Corrected runtime catalogue, owner assignment record and picker saved choices. TRC/NBPD retain existing sirens. All prior115 native wiring checks remain applicable to unchanged audio sources;13 focused correction checks PASS for exact Glock source on both sides, spatial anchors, actual native loop wrap, distinct mapping and Union/authority preservation. Current source hashes recorded. Full final faction/title/artist table and validation limits: tools/faction_music_apply_20260915/README.md.\n\nNo decisions remain. Next: scoped commit/push and remote hash verification; reopen normal live-source sandbox for faction playback. Preserve current concurrent portrait/Arsenal/Harold/range work, including any staged changes. No runtime menu or audio asset edits in this block. Supersedes apply-02 pending duplicate decision. The utility remains local and reopenable; active in-memory picker sessions should be reopened to display the corrected saved mapping.\n'
for name in ['DEAD_STREET_HIVE_MIND.md','DEAD_STREET_JOURNAL.md','DEAD_STREET_PROJECT_CONTROL.md']:
    path=root/'docs'/name
    if '## 20260915-faction-music-apply-03' not in path.read_text(encoding='utf-8'):
        with path.open('a',encoding='utf-8') as f:f.write(entry)
    assert entry in path.read_text(encoding='utf-8')
print('FINAL_RECORDS_SAVED; PUBLISH_PREPARED',flush=True)
