from pathlib import Path
import json,subprocess
out=Path(__file__).resolve().parent;root=out.parents[1]
v=json.loads((out/'native_validation.json').read_text());assert len(v['checks'])==115 and not v['failures'] and all(v['checks'].values())
a=json.loads((out/'approved_assignments.json').read_text(encoding='utf-8'))
a['status']='awaiting_duplicate_resolution';a['pending_decision']='Owner says repeated Burn was unintended. Glock — B-22 is unused. Need whether Calle Ocho or La Union del Sur receives Glock; do not guess or publish provisional mapping.'
(out/'approved_assignments.json').write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
readme='# Faction music integration — duplicate correction pending\n\nRuntime audio wiring is implemented and passes 115 native checks. Owner returned all 21 screenshot assignments, then clarified repeating Burn was accidental. Glock — B-22 is unused. Await whether Calle Ocho or La Unión del Sur receives Glock. Current local catalogue retains the screenshot mapping provisionally; DO NOT publish it as final.\n\n'
readme+='| Faction | Track | Artist |\n| --- | --- | --- |\n'
for row in a['assignments']:readme+='| '+row['faction']+' | '+row['track']+' | '+row['artist']+' |\n'
readme+='\nTRC and NBPD keep existing sirens. No menu track/audio file changes. Each mapped side uses its loop from the catalogue: defenders at the Harold/estate building entrance, other sides at convoy transport with a fixed-position fallback for no vehicle. Same stream continues through winning outro. Old apartment beat suppressed when mapped faction music is present. Authority source data, loop flags, gain, pitch, range, attenuation, panning and metadata compare exactly with the previous implementation across all three maps. All 21 current mapped factions tested on both sides and native 30-second wraps; all three live battle fixtures checked.\n\nEvidence: native_validation.json, source_hashes.json, protected_hashes.json, approved_assignments.json, runtime.patch, check_native.gd. Initial missing-declaration runtime error fixed; subsequent harness was isolated from rendering and given a proper result fixture, final 115/115 passed. Earlier failed logs retained. No subjective listening/mix approval claim. No commit or push performed for this task. Next: resolve duplicate; update catalogue and owner snapshot, check corrected faction/Glock playback and final uniqueness; update shared records, then scoped publication. Stage only owned audio source deltas, catalogue and evidence/owned shared records; preserve concurrent range/portrait work.\n'
(out/'README.md').write_text(readme,encoding='utf-8',newline='\n')
entry='\n\n## 20260915-faction-music-apply-02 - Wiring validated; owner correcting duplicated Burn\n\nIMPLEMENTED / NATIVE-VALIDATED audio wiring: 115 checks PASS, zero final failures. All21 screenshot mappings load on both sides and loop; actual Harold/bridge/estate sources and anchors, winning-stream continuity, loser background, exit stop and suppression of old Harold beat checked. TRC/NBPD audio/parameters match previous implementation across all three maps. Existing menu tracks/audio assets and protected consumers unchanged. Initial declaration bug fixed; harness isolation/result fixture corrections documented in tools/faction_music_apply_20260915/README.md. No commit/push performed.\n\nLATEST OWNER CORRECTION: repeated Burn was NOT intentional. Unused track is Glock — B-22. Current screenshot has Burn for Calle Ocho and La Union del Sur. Exact unresolved choice is which of those two gets Glock. Do not infer, publish or claim final assignment approval before this is answered. Current catalogue remains provisional screenshot mapping; approved_assignments.json status now awaiting_duplicate_resolution. Next: receive selection, update that single faction to glock_b22 and check uniqueness/corrected source; preserve the other20 choices and both authority sirens. Then finalize owned records and scoped publication. Hive/current source supersedes earlier apply-01 assertion that duplicated Burn was an approved final choice.\n'
for name in ['DEAD_STREET_JOURNAL.md','DEAD_STREET_HIVE_MIND.md','DEAD_STREET_PROJECT_CONTROL.md']:
    p=root/'docs'/name
    if '## 20260915-faction-music-apply-02' not in p.read_text(encoding='utf-8'):
        with p.open('a',encoding='utf-8') as f:f.write(entry)
    assert entry in p.read_text(encoding='utf-8')
print('VALIDATED_115; DUPLICATE_DECISION_RECORDED; STAGED',subprocess.check_output(['git','diff','--cached','--name-only'],cwd=root,text=True).strip() or '(empty)',flush=True)
