from pathlib import Path
import subprocess,sys,json,shutil,hashlib
r=Path(r'C:\Users\brand\OneDrive\Documents\dead-street');o=r/'tools/raiders_recording';base=Path(r'C:\Users\brand\AppData\Local\DeadStreetTools\godot_release_4.7.2')
(r/'tools/convoy_arrival/build_audio.py').write_bytes('"""Build convoy ambience from a credited performed guitar recording and original siren."""\nfrom pathlib import Path\nimport hashlib,subprocess,wave\nimport numpy as np\nimport imageio_ffmpeg\nSR=44100\nSOURCE_SHA256=\'8e029adfdf35f2fb5b4a88958b2ce3194c3f0672ffe94ffa69f3f8f3a998d0bd\'\ndef lowpass(a,hz):\n f=np.fft.rfftfreq(len(a),1/SR);response=1/np.sqrt(1+(f/hz)**6)\n return np.fft.irfft(np.fft.rfft(a)*response,n=len(a))\ndef siren():\n t=np.arange(12*SR)/SR;freq=760+260*np.sin(2*np.pi*t/4.-np.pi/2);phase=2*np.pi*np.cumsum(freq)/SR\n a=np.sin(phase)+.26*np.sin(3*phase)+.12*np.sin(5*phase)\n a=lowpass(a,1450)*(.84+.16*np.sin(2*np.pi*t/.19));return a/np.max(np.abs(a))*.6\n\ndef save(path,a):\n path.parent.mkdir(parents=True,exist_ok=True);edge=min(int(.035*SR),len(a)//2)\n a[:edge]*=np.linspace(0,1,edge);a[-edge:]*=np.linspace(1,0,edge)\n with wave.open(str(path),\'wb\')as w:\n  w.setparams((1,2,SR,len(a),\'NONE\',\'not compressed\'));w.writeframes(np.rint(np.clip(a,-1,1)*32767).astype(\'<i2\').tobytes())\nif __name__==\'__main__\':\n root=Path(__file__).resolve().parents[2];out=root/\'assets/audio/convoy\';source=Path(__file__).parent/\'sources/thrash_metal_thunderstorm10.mp3\'\n assert hashlib.sha256(source.read_bytes()).hexdigest()==SOURCE_SHA256\n # Lower tuning and slower pulse; retain the recorded pick/amp/drum transients.\n # Narrow radio bandwidth leaves enough upper midrange for distorted guitar grit.\n effects=\'asetrate=39290,aresample=44100,atempo=0.76,highpass=f=150,lowpass=f=2700,equalizer=f=950:t=q:w=0.8:g=2\'\n raw=subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(),\'-hide_banner\',\'-loglevel\',\'error\',\'-i\',str(source),\'-af\',effects,\'-ac\',\'1\',\'-ar\',str(SR),\'-f\',\'f32le\',\'-\'],capture_output=True,check=True).stdout\n a=np.frombuffer(raw,dtype=\'<f4\').copy();assert np.isfinite(a).all();a*=.78/max(float(np.max(np.abs(a))),1e-9)\n save(out/\'raiders_radio.wav\',a);save(out/\'police_siren.wav\',siren())\n print(\'RECORDED_GUITAR_READY\',len(a)/SR,flush=True)\n'.encode())
(r/'assets/audio/convoy/CREDITS.md').write_bytes('# Convoy radio credit\n\n"Thrash Metal Backing Track.mp3" by thunderstorm10, 2016.\nSource: https://freesound.org/people/thunderstorm10/sounds/367876/\nLicense: Creative Commons Attribution 3.0 — https://creativecommons.org/licenses/by/3.0/\nPublic preview: https://cdn.freesound.org/previews/367/367876_4162634-hq.mp3\nSource SHA256: 8e029adfdf35f2fb5b4a88958b2ce3194c3f0672ffe94ffa69f3f8f3a998d0bd\n\nAuthor describes the guitar as their own performance through Guitar Rig 5 and drums made with Rhythm Rascal.\nDead Street adaptation: lowered pitch, slowed tempo, mono radio filtering, level normalization and short loop-edge ramps. This is an adaptation, not the unmodified source, and the artist does not endorse the game. Source is preserved under tools/convoy_arrival/sources. The prior synthetic riff is superseded.\nThe police siren is an original procedural asset. No Pantera recording is used.\n'.encode())
src=r/'tools/convoy_arrival/sources/thrash_metal_thunderstorm10.mp3';src.parent.mkdir(exist_ok=True);shutil.copy2(o/'music_367876.mp3',src)
subprocess.run([sys.executable,str(r/'tools/convoy_arrival/build_audio.py')],cwd=r,check=True,timeout=40)
p=r/'tools/tactical_controls/raiders_director.gd';s=p.read_text();s=s.replace('static func config()','const Armor=preload("res://campaign/equipment/armor_catalog.gd")\nstatic func config()');s=s.replace(' for side in ["attacker","defender"]:\n  var roles=', ' var strongest_armor="patrol_vest"\n for id in Armor.IDS:\n  if Armor.bonus(id)>Armor.bonus(strongest_armor):strongest_armor=id\n for side in ["attacker","defender"]:\n  var roles=');s=s.replace('row.armor="patrol_vest"','row.armor=strongest_armor if side=="attacker" else ""');p.write_bytes(s.encode())
p=r/'tools/tactical_controls/raiders_record.gd';s=p.read_text().replace('Vector2(-552,53)','Vector2(-552,-55)');s=s.replace('var trim_frames=0','var trim_frames=0\nvar credit_label: Label')
s=s.replace(' if not started:\n', ' if presentation.results_visible() and credit_label==null:\n  credit_label=Label.new();root.add_child(credit_label)\n  credit_label.text="Radio: Thrash Metal Backing Track — thunderstorm10 / CC BY 3.0\\nAdapted: pitch, tempo, radio filter. freesound.org/s/367876/"\n  credit_label.position=Vector2(26,1012);credit_label.add_theme_font_size_override("font_size",18)\n  credit_label.add_theme_color_override("font_color",Color(.8,.8,.76))\n if not started:\n')
p.write_bytes(s.encode())
p=r/'tools/tactical_controls/convoy_native.gd';p.write_bytes(p.read_text().replace('Vector2(-550,86)','Vector2(-550,-22)').encode())
subprocess.run([sys.executable,str(r/'tools/tactical_controls/run.py'),'pack'],cwd=r,check=True,timeout=90)
chosen=None
for seed in [9141,9142,9143,9144]:
 with(o/f'winning_probe_{seed}.log').open('wb')as f:
  p=subprocess.run([str(base/'godot.exe'),'--headless','--','--check=raiders_probe',f'--seed={seed}'],cwd=r,stdout=f,stderr=subprocess.STDOUT,timeout=90)
 log=(o/f'winning_probe_{seed}.log').read_text(encoding='utf-8',errors='replace');assert p.returncode==0 and 'SCRIPT ERROR'not in log and '\nERROR:'not in log,log[-3000:]
 report=json.loads((o/'probe.json').read_text());print('WIN_CHECK',seed,report['winner'],report['duration'],flush=True)
 if report['phase']=='resolved' and report['winner']=='attacker':chosen=seed;break
assert chosen is not None,'No winning showcase fixture within bounded seed check'
p=r/'tools/tactical_controls/raiders_record.gd';p.write_bytes(p.read_text().replace('9141',str(chosen)).encode())
# Only the recorder fixture/seed is shaped; global combat remains untouched.
print('READY_TO_RECORD',chosen,flush=True)
